INSERT INTO `quetes` VALUES ('525', 'Le divin enfant.');
INSERT INTO `quetes` VALUES ('446', 'Le forgeron aux deux mains gauches.');
INSERT INTO `quetes` VALUES ('118', 'Retrouver Zatoïshwan');
INSERT INTO `quetes` VALUES ('631', 'Epis d\'Emi.');
INSERT INTO `quetes` VALUES ('298', 'Course-poursuite.');
INSERT INTO `quetes` VALUES ('634', 'Groméo et Ginette.');
INSERT INTO `quetes` VALUES ('635', 'Une blague vaseuse ?');
INSERT INTO `quetes` VALUES ('272', 'Assassinat effectué.');
INSERT INTO `quetes` VALUES ('636', 'Blessure de chasse.');
INSERT INTO `quetes` VALUES ('637', 'Chasse dangereuse.');
INSERT INTO `quetes` VALUES ('638', 'Rentrer brocouille.');
INSERT INTO `quetes` VALUES ('639', 'Un chasseur qui a du coffre.');
INSERT INTO `quetes` VALUES ('640', 'Un volcan s\'éteint.');
INSERT INTO `quetes` VALUES ('641', 'L\'abominable YeCh\'Ti.');
INSERT INTO `quetes` VALUES ('642', 'Bonmonstres de neige.');
INSERT INTO `quetes` VALUES ('643', 'Manque de re-peau.');
INSERT INTO `quetes` VALUES ('644', 'Le convoi, le sage aussi.');
INSERT INTO `quetes` VALUES ('222', 'Suite Woyale');
INSERT INTO `quetes` VALUES ('68', 'De la poudre aux yeux de Brâkmar');
INSERT INTO `quetes` VALUES ('76', 'La fureur du Holbaïd');
INSERT INTO `quetes` VALUES ('63', 'Première visite à Brâkmar');
INSERT INTO `quetes` VALUES ('290', 'Trâknar.');
INSERT INTO `quetes` VALUES ('278', 'A la manière des Brâkmariens.');
INSERT INTO `quetes` VALUES ('265', 'Quand y\'en a marre de Brâkmar.');
INSERT INTO `quetes` VALUES ('26', 'Manuscrit de Terra Cogita');
INSERT INTO `quetes` VALUES ('60', 'Cartes spéciales d\'Amayiro');
INSERT INTO `quetes` VALUES ('78', 'Corvée de patate');
INSERT INTO `quetes` VALUES ('81', 'Amayiro à l\'ombre du Champo');
INSERT INTO `quetes` VALUES ('161', 'Pinta Gone veut se remplir de bière Bwork');
INSERT INTO `quetes` VALUES ('302', 'Bandanarthrie.');
INSERT INTO `quetes` VALUES ('299', 'A la poursuite d\'Octolliard rouge.');
INSERT INTO `quetes` VALUES ('262', 'Alimentaire mon cher.');
INSERT INTO `quetes` VALUES ('519', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('89', 'Danathor a-t-il tort ?');
INSERT INTO `quetes` VALUES ('261', 'Dans la gueule du chat.');
INSERT INTO `quetes` VALUES ('85', 'Des combats pas très légaux...');
INSERT INTO `quetes` VALUES ('65', 'Du repos mais pas trop...');
INSERT INTO `quetes` VALUES ('88', 'La lettre anonyme');
INSERT INTO `quetes` VALUES ('486', 'Le secret de Percimol');
INSERT INTO `quetes` VALUES ('400', 'Activités volcaniques.');
INSERT INTO `quetes` VALUES ('387', 'Agent double et demi.');
INSERT INTO `quetes` VALUES ('392', 'Alchimie malfaisante.');
INSERT INTO `quetes` VALUES ('175', 'Allez, au turbin.');
INSERT INTO `quetes` VALUES ('206', 'Allez, au turbin.');
INSERT INTO `quetes` VALUES ('207', 'Allez, au turbin.');
INSERT INTO `quetes` VALUES ('120', 'Apprentissage : Chevalier de l\'Espoir');
INSERT INTO `quetes` VALUES ('291', 'Attaque à retardement.');
INSERT INTO `quetes` VALUES ('188', 'Battre le blé.');
INSERT INTO `quetes` VALUES ('404', 'Bois de chauffage.');
INSERT INTO `quetes` VALUES ('448', 'Bonta a besoin de vous.');
INSERT INTO `quetes` VALUES ('447', 'Brâkmar a besoin de vous.');
INSERT INTO `quetes` VALUES ('401', 'Chasse à l\'espion.');
INSERT INTO `quetes` VALUES ('458', 'Chasse au dopeul Crâ.');
INSERT INTO `quetes` VALUES ('285', 'La panoplie du milicien.');
INSERT INTO `quetes` VALUES ('459', 'Chasse au dopeul Ecaflip.');
INSERT INTO `quetes` VALUES ('462', 'Chasse au dopeul Eniripsa.');
INSERT INTO `quetes` VALUES ('464', 'Chasse au dopeul Enutrof.');
INSERT INTO `quetes` VALUES ('469', 'Chasse au dopeul Féca.');
INSERT INTO `quetes` VALUES ('460', 'Chasse au dopeul Iop.');
INSERT INTO `quetes` VALUES ('461', 'Chasse au dopeul Osamodas.');
INSERT INTO `quetes` VALUES ('466', 'Chasse au dopeul Pandawa.');
INSERT INTO `quetes` VALUES ('463', 'Chasse au dopeul Sacrieur.');
INSERT INTO `quetes` VALUES ('465', 'Chasse au dopeul Sadida.');
INSERT INTO `quetes` VALUES ('467', 'Chasse au dopeul Sram.');
INSERT INTO `quetes` VALUES ('468', 'Chasse au dopeul Xélor.');
INSERT INTO `quetes` VALUES ('375', 'Cliquetis fou.');
INSERT INTO `quetes` VALUES ('313', 'Contre-espion.');
INSERT INTO `quetes` VALUES ('209', 'Crypte Honnie');
INSERT INTO `quetes` VALUES ('268', 'Dans la peau de Sphincter Cell.');
INSERT INTO `quetes` VALUES ('393', 'Des capes typiques.');
INSERT INTO `quetes` VALUES ('185', 'Eau du bain.');
INSERT INTO `quetes` VALUES ('306', 'Enquête à Moon.');
INSERT INTO `quetes` VALUES ('74', 'Le fantôme de Tsog');
INSERT INTO `quetes` VALUES ('82', 'Le décès de Rimaraf');
INSERT INTO `quetes` VALUES ('94', 'Les rats d\'Hyoactif');
INSERT INTO `quetes` VALUES ('333', 'Le subterfuge de la corne.');
INSERT INTO `quetes` VALUES ('50', 'Flêches Cra-rakneene');
INSERT INTO `quetes` VALUES ('9', 'Grain de folie à Astrub');
INSERT INTO `quetes` VALUES ('314', 'Histoires de salaces.');
INSERT INTO `quetes` VALUES ('296', 'Histoires de tortues.');
INSERT INTO `quetes` VALUES ('411', 'Humiliation sans précédent.');
INSERT INTO `quetes` VALUES ('39', 'Initiation à la nature... des Sadidas.');
INSERT INTO `quetes` VALUES ('174', 'Instincts primaires.');
INSERT INTO `quetes` VALUES ('294', 'Investigations à Moon.');
INSERT INTO `quetes` VALUES ('251', 'Joyau... ze fête.');
INSERT INTO `quetes` VALUES ('495', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('496', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('497', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('498', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('56', 'La tenancière Dame Cloude');
INSERT INTO `quetes` VALUES ('499', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('500', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('501', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('502', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('504', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('505', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('506', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('507', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('508', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('509', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('510', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('511', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('512', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('513', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('514', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('515', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('516', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('517', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('518', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('79', 'Lyeno, Abraknyde malgré lui');
INSERT INTO `quetes` VALUES ('91', 'Leçon de cuisine');
INSERT INTO `quetes` VALUES ('520', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('521', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('522', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('193', 'La clef du donjon.');
INSERT INTO `quetes` VALUES ('289', 'La Grafioze.');
INSERT INTO `quetes` VALUES ('381', 'La mise à mort.');
INSERT INTO `quetes` VALUES ('380', 'La noirceur des armes blanches.');
INSERT INTO `quetes` VALUES ('254', 'La punition de l\'incompétent.');
INSERT INTO `quetes` VALUES ('379', 'La revanche de Mak.');
INSERT INTO `quetes` VALUES ('284', 'La tactique des gens d\'armes.');
INSERT INTO `quetes` VALUES ('267', 'Le carnage des plaines.');
INSERT INTO `quetes` VALUES ('384', 'Le con tondant.');
INSERT INTO `quetes` VALUES ('252', 'Le cristal de Kain Dharyn.');
INSERT INTO `quetes` VALUES ('403', 'Le défi du maître guerrier.');
INSERT INTO `quetes` VALUES ('378', 'Le dentiste dément.');
INSERT INTO `quetes` VALUES ('398', 'Le dur travail d\'éplucheur de patates.');
INSERT INTO `quetes` VALUES ('494', 'Le Grand Manitou.');
INSERT INTO `quetes` VALUES ('295', 'Manière douce.');
INSERT INTO `quetes` VALUES ('273', 'Le magnanime.');
INSERT INTO `quetes` VALUES ('256', 'Le moment de vérité.');
INSERT INTO `quetes` VALUES ('280', 'Le port salue.');
INSERT INTO `quetes` VALUES ('376', 'Le professionnel.');
INSERT INTO `quetes` VALUES ('391', 'Le tabi mangeur de blops.');
INSERT INTO `quetes` VALUES ('394', 'Le testament du papa.');
INSERT INTO `quetes` VALUES ('279', 'Le trésor de La Descemer.');
INSERT INTO `quetes` VALUES ('317', 'Légitime défense.');
INSERT INTO `quetes` VALUES ('281', 'L\'équipe ment.');
INSERT INTO `quetes` VALUES ('445', 'Les 7 bandits.');
INSERT INTO `quetes` VALUES ('310', 'Les documents avant tout.');
INSERT INTO `quetes` VALUES ('258', 'Les Ecas ne flippent pas.');
INSERT INTO `quetes` VALUES ('382', 'Les gardes d\'honneur... à punir.');
INSERT INTO `quetes` VALUES ('274', 'Les kamas résolvent tout.');
INSERT INTO `quetes` VALUES ('406', 'L\'espionnage nouveau.');
INSERT INTO `quetes` VALUES ('439', 'L\'éternelle moisson.');
INSERT INTO `quetes` VALUES ('255', 'Livraison rapide.');
INSERT INTO `quetes` VALUES ('388', 'Livreur de mauvaise nouvelle.');
INSERT INTO `quetes` VALUES ('307', 'Manière forte.');
INSERT INTO `quetes` VALUES ('176', 'Manufacture.');
INSERT INTO `quetes` VALUES ('202', 'Manufacture.');
INSERT INTO `quetes` VALUES ('203', 'Manufacture.');
INSERT INTO `quetes` VALUES ('204', 'Manufacture.');
INSERT INTO `quetes` VALUES ('62', 'Pas de fainéants dans les rangs !');
INSERT INTO `quetes` VALUES ('192', 'Marché équitable.');
INSERT INTO `quetes` VALUES ('180', 'Milice populaire.');
INSERT INTO `quetes` VALUES ('102', 'Pandawa et fier de l\'être');
INSERT INTO `quetes` VALUES ('181', 'Papotage.');
INSERT INTO `quetes` VALUES ('259', 'Plaine de chats.');
INSERT INTO `quetes` VALUES ('283', 'Pour vivre heureux.');
INSERT INTO `quetes` VALUES ('70', 'Quatre caisses à pied, ça use...');
INSERT INTO `quetes` VALUES ('172', 'Premières armes.');
INSERT INTO `quetes` VALUES ('194', 'Restauration.');
INSERT INTO `quetes` VALUES ('308', 'Retour aux origines.');
INSERT INTO `quetes` VALUES ('189', 'Salut les copains.');
INSERT INTO `quetes` VALUES ('198', 'Spéléologie.');
INSERT INTO `quetes` VALUES ('162', 'Un avenir de krotte de Trooll');
INSERT INTO `quetes` VALUES ('470', 'Un bon gros par Douze.');
INSERT INTO `quetes` VALUES ('412', 'Un choix difficile.');
INSERT INTO `quetes` VALUES ('377', 'Un coup de fouet.');
INSERT INTO `quetes` VALUES ('249', 'La récompense du compétent.');
INSERT INTO `quetes` VALUES ('405', 'L\'équipement du traine-savate standard.');
INSERT INTO `quetes` VALUES ('410', 'Un dentier pour l\'ami Mak.');
INSERT INTO `quetes` VALUES ('271', 'Un maître ès pion.');
INSERT INTO `quetes` VALUES ('399', 'Cruel, mais à quel point ?');
INSERT INTO `quetes` VALUES ('383', 'Un oubli regrettable.');
INSERT INTO `quetes` VALUES ('402', 'Un petit oubli.');
INSERT INTO `quetes` VALUES ('304', 'Un sombre pouvoir.');
INSERT INTO `quetes` VALUES ('440', 'Une collecte discutable.');
INSERT INTO `quetes` VALUES ('389', 'Une collection digne de Xilébo.');
INSERT INTO `quetes` VALUES ('303', 'Une Corne Edfrit sans sel.');
INSERT INTO `quetes` VALUES ('390', 'La chasse, tout un art...');
INSERT INTO `quetes` VALUES ('282', 'Une partie de cache-cache.');
INSERT INTO `quetes` VALUES ('305', 'Une rumeur alléchante.');
INSERT INTO `quetes` VALUES ('492', 'Vaincre le monstre.');
INSERT INTO `quetes` VALUES ('247', 'X comme Xephirès.');
INSERT INTO `quetes` VALUES ('386', 'Mais si, ce sont des vitamines...');
INSERT INTO `quetes` VALUES ('270', 'Mon nom est poison.');
INSERT INTO `quetes` VALUES ('312', 'On m\'appelle l\'Escargot');
INSERT INTO `quetes` VALUES ('248', 'Opération commando.');
INSERT INTO `quetes` VALUES ('277', 'Paranoïa aigüe.');
INSERT INTO `quetes` VALUES ('408', 'Pauvre larve.');
INSERT INTO `quetes` VALUES ('409', 'Pauvre larve... dorée.');
INSERT INTO `quetes` VALUES ('250', 'Rencontre du premier type.');
INSERT INTO `quetes` VALUES ('385', 'Sombres échanges.');
INSERT INTO `quetes` VALUES ('275', 'Supermilicien.');
INSERT INTO `quetes` VALUES ('396', 'Taxe gratuite.');
INSERT INTO `quetes` VALUES ('246', 'Triple X.');
INSERT INTO `quetes` VALUES ('433', 'Apprentissage : Disciple de Ménalt');
INSERT INTO `quetes` VALUES ('434', 'Apprentissage : Disciple de Jiva');
INSERT INTO `quetes` VALUES ('436', 'Apprentissage : Disciple de Djaul');
INSERT INTO `quetes` VALUES ('438', 'Apprentissage : Disciple de Brumaire');
INSERT INTO `quetes` VALUES ('123', 'Apprentissage : Chevalier du Désespoir');
INSERT INTO `quetes` VALUES ('437', 'Apprentissage : Disciple d\'Hécate');
INSERT INTO `quetes` VALUES ('503', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('530', 'On se lève tous pour Annette.');
INSERT INTO `quetes` VALUES ('531', 'Michons fleuris.');
INSERT INTO `quetes` VALUES ('532', 'Heureusement il a faim, Duss.');
INSERT INTO `quetes` VALUES ('533', 'Mines anti-personnel.');
INSERT INTO `quetes` VALUES ('534', 'Mmmh, Shab Al.');
INSERT INTO `quetes` VALUES ('535', 'Chaudière au charbon.');
INSERT INTO `quetes` VALUES ('536', 'Michel Shel enquille un Bouftonmouth.');
INSERT INTO `quetes` VALUES ('537', 'Espèce menacée.');
INSERT INTO `quetes` VALUES ('538', 'Pied joyeux.');
INSERT INTO `quetes` VALUES ('539', 'La mort vous va si bien.');
INSERT INTO `quetes` VALUES ('540', 'Passe ta larme à gauche.');
INSERT INTO `quetes` VALUES ('541', 'Une mine patibulaire.');
INSERT INTO `quetes` VALUES ('542', 'Pauvre Kiki.');
INSERT INTO `quetes` VALUES ('543', 'La marche de l\'impératrice.');
INSERT INTO `quetes` VALUES ('544', 'On recherche CHAMPS.');
INSERT INTO `quetes` VALUES ('545', 'On recherche Monsieur Pingouin.');
INSERT INTO `quetes` VALUES ('546', 'On recherche FORÊT PINS.');
INSERT INTO `quetes` VALUES ('547', 'On recherche Fantômayte.');
INSERT INTO `quetes` VALUES ('548', 'On recherche Vengeuse Masquée.');
INSERT INTO `quetes` VALUES ('549', 'On recherche le YeCh\'Ti.');
INSERT INTO `quetes` VALUES ('170', 'Ange de Gobriel');
INSERT INTO `quetes` VALUES ('186', 'Ca va couper, chérie.');
INSERT INTO `quetes` VALUES ('183', 'Bienvenue !');
INSERT INTO `quetes` VALUES ('184', 'Piou ?');
INSERT INTO `quetes` VALUES ('173', 'Soyez Aouaire !');
INSERT INTO `quetes` VALUES ('182', 'Zaap de là !');
INSERT INTO `quetes` VALUES ('225', 'Qui veut la peau du Wabbit?');
INSERT INTO `quetes` VALUES ('211', 'Traître ou pas traître, telle est la question...');
INSERT INTO `quetes` VALUES ('140', 'Mais où est passé le Minotoror ?');
INSERT INTO `quetes` VALUES ('315', 'Affrontement !');
INSERT INTO `quetes` VALUES ('144', 'Chargez !');
INSERT INTO `quetes` VALUES ('309', 'Une faille dans sa carapace.');
INSERT INTO `quetes` VALUES ('395', 'Amadouer ou corrompre ?');
INSERT INTO `quetes` VALUES ('397', 'Par la force ou par la finesse ?');
INSERT INTO `quetes` VALUES ('407', 'Un assassin... chez Bonta ?');
INSERT INTO `quetes` VALUES ('526', 'Laisse pas trainer tes fils.');
INSERT INTO `quetes` VALUES ('527', 'Laisse pas trainer tes fils.');
INSERT INTO `quetes` VALUES ('528', 'Le Grand oeuvre.');
INSERT INTO `quetes` VALUES ('257', 'Vin diou.');
INSERT INTO `quetes` VALUES ('293', 'Une rumeur intéressante.');
INSERT INTO `quetes` VALUES ('72', 'La foire du Trool suspectée');
INSERT INTO `quetes` VALUES ('100', 'Pandala, son air pur...');
INSERT INTO `quetes` VALUES ('488', 'Sanctification.');
INSERT INTO `quetes` VALUES ('554', 'Gène et tique.');
INSERT INTO `quetes` VALUES ('555', 'Un gros cube, un p\'ti cube.');
INSERT INTO `quetes` VALUES ('556', 'En semant se ment.');
INSERT INTO `quetes` VALUES ('276', 'Le forgeron.');
INSERT INTO `quetes` VALUES ('557', 'Pomdeupin vaut mieux que trois tu l\'auras.');
INSERT INTO `quetes` VALUES ('558', 'Massacre au hakapik.');
INSERT INTO `quetes` VALUES ('559', 'Mettre son grain de sel.');
INSERT INTO `quetes` VALUES ('560', 'Mauvaise graine.');
INSERT INTO `quetes` VALUES ('561', 'Champ Pomy.');
INSERT INTO `quetes` VALUES ('562', 'Gant graine.');
INSERT INTO `quetes` VALUES ('566', 'Cent vingt trois fleurs, point comme les autres.');
INSERT INTO `quetes` VALUES ('567', 'Botanique-nique-nique.');
INSERT INTO `quetes` VALUES ('568', 'A fleur de peau.');
INSERT INTO `quetes` VALUES ('569', 'Mes lys fleurs.');
INSERT INTO `quetes` VALUES ('570', 'Rose à lys, Rose à lys, oh !');
INSERT INTO `quetes` VALUES ('571', 'Fleuries mais rougissent.');
INSERT INTO `quetes` VALUES ('572', 'Heureux qui, comme les lys.');
INSERT INTO `quetes` VALUES ('576', 'Signé Ernest Laye.');
INSERT INTO `quetes` VALUES ('577', 'Pêche en eaux gelées.');
INSERT INTO `quetes` VALUES ('578', 'La pêche à Mel.');
INSERT INTO `quetes` VALUES ('579', 'Il est frais mon pichon.');
INSERT INTO `quetes` VALUES ('580', 'Vacances sur glace.');
INSERT INTO `quetes` VALUES ('581', 'Hôtel de glace.');
INSERT INTO `quetes` VALUES ('582', 'La fonte des glaces.');
INSERT INTO `quetes` VALUES ('583', 'L\'ombre et la glace.');
INSERT INTO `quetes` VALUES ('584', 'Adoption éphémère.');
INSERT INTO `quetes` VALUES ('589', 'Bricole Girl.');
INSERT INTO `quetes` VALUES ('590', 'Promenons-nous dans les bois.');
INSERT INTO `quetes` VALUES ('591', 'Les chasseurs.');
INSERT INTO `quetes` VALUES ('592', 'Il préfère la mort en mer.');
INSERT INTO `quetes` VALUES ('599', 'Souvenir, souvenir.');
INSERT INTO `quetes` VALUES ('593', 'Chauffage à moindre frais.');
INSERT INTO `quetes` VALUES ('594', 'A la recherche de Danlavie.');
INSERT INTO `quetes` VALUES ('600', 'Bricoleur de génie.');
INSERT INTO `quetes` VALUES ('601', 'Bijoux de famille.');
INSERT INTO `quetes` VALUES ('595', 'LES RESCAPÉS DE FRIGOST 7');
INSERT INTO `quetes` VALUES ('602', 'Obscurantisme.');
INSERT INTO `quetes` VALUES ('6', '(next) A la recherche du Coup-devin');
INSERT INTO `quetes` VALUES ('612', 'La terre banquise.');
INSERT INTO `quetes` VALUES ('613', 'La maire de glace.');
INSERT INTO `quetes` VALUES ('614', 'Full contact.');
INSERT INTO `quetes` VALUES ('615', 'Les monologues du vaccin.');
INSERT INTO `quetes` VALUES ('616', 'Faire le tas de pins.');
INSERT INTO `quetes` VALUES ('617', 'Scierie Bambelle.');
INSERT INTO `quetes` VALUES ('618', 'Semer ses graines.');
INSERT INTO `quetes` VALUES ('619', 'Antiroyaliste.');
INSERT INTO `quetes` VALUES ('620', 'Les joyeux de la couronne.');
INSERT INTO `quetes` VALUES ('621', 'Fais dodo, t\'auras du gâteau.');
INSERT INTO `quetes` VALUES ('622', 'Lavomatique.');
INSERT INTO `quetes` VALUES ('4', 'La complainte du chacha');
INSERT INTO `quetes` VALUES ('5', 'De la difficulté à être Bijoutier');
INSERT INTO `quetes` VALUES ('7', 'Le dur labeur de Sram');
INSERT INTO `quetes` VALUES ('29', 'Retrouver Padgref Demoël');
INSERT INTO `quetes` VALUES ('10', 'Problème de livraison');
INSERT INTO `quetes` VALUES ('11', 'Pleur Nycheuz');
INSERT INTO `quetes` VALUES ('13', 'Un ours dans la bouftonerie');
INSERT INTO `quetes` VALUES ('14', 'La dernière mode');
INSERT INTO `quetes` VALUES ('15', 'Une taupe de trop dans mon Astrub');
INSERT INTO `quetes` VALUES ('18', 'Wogew l\'hewmite');
INSERT INTO `quetes` VALUES ('20', 'Epée : mode d\'emploi');
INSERT INTO `quetes` VALUES ('21', 'Forgée sur un pari. A l\'Ecaflip simplement');
INSERT INTO `quetes` VALUES ('24', 'Vol...Age ?');
INSERT INTO `quetes` VALUES ('25', 'Savoir de Crâ ');
INSERT INTO `quetes` VALUES ('30', 'Retrouver Frakacia Leukocytine');
INSERT INTO `quetes` VALUES ('31', 'Retrouver Nervoes Brakdoun');
INSERT INTO `quetes` VALUES ('33', 'Retrouver Brumen Tinctorias');
INSERT INTO `quetes` VALUES ('34', 'Retrouver Fouduglen L\'écureuil');
INSERT INTO `quetes` VALUES ('35', 'Retrouver Ogivol Scalarcin');
INSERT INTO `quetes` VALUES ('36', 'Bière en danger');
INSERT INTO `quetes` VALUES ('37', 'Futuramakna');
INSERT INTO `quetes` VALUES ('38', 'Les Enutrofs sont nos amis, il faut...');
INSERT INTO `quetes` VALUES ('40', 'Le Donjon de la reflexion');
INSERT INTO `quetes` VALUES ('43', 'Chasse à l\'écureuil');
INSERT INTO `quetes` VALUES ('44', 'Ne pas vendre la mèche avant de l\'avoir tuée');
INSERT INTO `quetes` VALUES ('45', 'A la recherche des Enus disparus');
INSERT INTO `quetes` VALUES ('47', 'Sandwich d\'Araknée');
INSERT INTO `quetes` VALUES ('48', 'Tofu sous microscope');
INSERT INTO `quetes` VALUES ('53', 'Pauvre Kwikwi');
INSERT INTO `quetes` VALUES ('55', 'Entraînement avec Tarche');
INSERT INTO `quetes` VALUES ('57', 'Du pain pour les braves');
INSERT INTO `quetes` VALUES ('58', 'Ned le dentiste');
INSERT INTO `quetes` VALUES ('59', 'Entraînement avec Torche');
INSERT INTO `quetes` VALUES ('61', 'On a volé le collier de la fille du maire');
INSERT INTO `quetes` VALUES ('64', 'Un sanglier un peu trop agressif...');
INSERT INTO `quetes` VALUES ('66', 'Recouvrement de dette à la Tabasse');
INSERT INTO `quetes` VALUES ('67', 'Pot l\'agent double');
INSERT INTO `quetes` VALUES ('69', 'Une brèche à Bonta');
INSERT INTO `quetes` VALUES ('71', 'L\'élite squelettique');
INSERT INTO `quetes` VALUES ('73', 'Le Tabi d\'Amayiro');
INSERT INTO `quetes` VALUES ('75', 'Des anneaux sur le bout des doigts');
INSERT INTO `quetes` VALUES ('77', 'Des capes Bontariennes');
INSERT INTO `quetes` VALUES ('80', 'Au service de Danathor');
INSERT INTO `quetes` VALUES ('83', 'Poison de scorbute pour la prison');
INSERT INTO `quetes` VALUES ('84', 'Dike Tarak, la menace');
INSERT INTO `quetes` VALUES ('86', 'Mission de reconnaissance au cimetière');
INSERT INTO `quetes` VALUES ('87', 'Extension du bâtiment de la milice');
INSERT INTO `quetes` VALUES ('90', 'Dix badges pour la bonne cause');
INSERT INTO `quetes` VALUES ('92', 'Ras le bol de Lenglad');
INSERT INTO `quetes` VALUES ('93', 'Dapyus n\'est pas doué ');
INSERT INTO `quetes` VALUES ('95', 'Pandala : une île pas comme les autres');
INSERT INTO `quetes` VALUES ('96', 'Plongée sous-marine');
INSERT INTO `quetes` VALUES ('98', 'Pandala: ses Villages...');
INSERT INTO `quetes` VALUES ('99', 'Sources étranges');
INSERT INTO `quetes` VALUES ('101', 'Henual et l\'Horloge divine');
INSERT INTO `quetes` VALUES ('103', 'Pandawa et fier de l\'être (Episode 2)');
INSERT INTO `quetes` VALUES ('104', 'Disciple Pandawushuka');
INSERT INTO `quetes` VALUES ('105', 'Pratiquant Pandawushuka');
INSERT INTO `quetes` VALUES ('106', 'Legende Lenalde');
INSERT INTO `quetes` VALUES ('107', 'Voir le Dark Vlad et ne pas mourir');
INSERT INTO `quetes` VALUES ('108', 'Mystères à Pandala');
INSERT INTO `quetes` VALUES ('109', 'Apprentissage : Ecuyer ');
INSERT INTO `quetes` VALUES ('110', 'Apprentissage : Espion');
INSERT INTO `quetes` VALUES ('111', 'Apprentissage : Apprenti');
INSERT INTO `quetes` VALUES ('112', 'Apprentissage : Surineur');
INSERT INTO `quetes` VALUES ('113', 'Apprentissage : Espion Sombre');
INSERT INTO `quetes` VALUES ('114', 'Apprentissage : Apprenti Sombre');
INSERT INTO `quetes` VALUES ('115', 'Retrouver Rok Gnorok');
INSERT INTO `quetes` VALUES ('116', 'Retrouver Musha l\'Oni');
INSERT INTO `quetes` VALUES ('117', 'Retrouver Marzwel le Gobelin');
INSERT INTO `quetes` VALUES ('119', 'Aermyne \'Braco\' Scalptaras');
INSERT INTO `quetes` VALUES ('121', 'Apprentissage : Adepte des Ecrits');
INSERT INTO `quetes` VALUES ('122', 'Apprentissage : Chasseur de Renégats');
INSERT INTO `quetes` VALUES ('124', 'Apprentissage : Adepte des Douleurs');
INSERT INTO `quetes` VALUES ('125', 'Apprentissage : Chasseur d\'Âmes');
INSERT INTO `quetes` VALUES ('126', 'L\'arche de Nowa');
INSERT INTO `quetes` VALUES ('127', 'Le livre d\'Acidrik Fenlapanse');
INSERT INTO `quetes` VALUES ('128', 'Le prêtre et la tête de Menalt');
INSERT INTO `quetes` VALUES ('129', 'A la recherche de l\'éleveur');
INSERT INTO `quetes` VALUES ('130', 'Les prisonniers d\'Astrub');
INSERT INTO `quetes` VALUES ('131', 'Visite guidée au château d\'Allister');
INSERT INTO `quetes` VALUES ('132', 'Gros oeuvres au château d\'Allister');
INSERT INTO `quetes` VALUES ('133', 'Kartier Tremai se met à table');
INSERT INTO `quetes` VALUES ('134', 'Les Dents de la Mère Verumacha');
INSERT INTO `quetes` VALUES ('135', 'La potion de lèche-bottes');
INSERT INTO `quetes` VALUES ('136', 'Comment mettre un requin en bière');
INSERT INTO `quetes` VALUES ('137', 'La belle ermite');
INSERT INTO `quetes` VALUES ('138', 'Pauvre pomme (de terre)');
INSERT INTO `quetes` VALUES ('139', 'De la viande de Dragodinde pour la tablée d\'Allister');
INSERT INTO `quetes` VALUES ('141', 'Culture et élevage');
INSERT INTO `quetes` VALUES ('142', 'La plume est plus forte... parfois');
INSERT INTO `quetes` VALUES ('145', 'Piétine titine');
INSERT INTO `quetes` VALUES ('146', 'Visite non guidée');
INSERT INTO `quetes` VALUES ('147', 'Des fleurs épineuses');
INSERT INTO `quetes` VALUES ('148', 'Epicerie fine');
INSERT INTO `quetes` VALUES ('149', 'Course polaire');
INSERT INTO `quetes` VALUES ('150', 'Charger la mule');
INSERT INTO `quetes` VALUES ('151', 'Tire laine');
INSERT INTO `quetes` VALUES ('152', 'Le tour du monde');
INSERT INTO `quetes` VALUES ('153', 'Le maître des clefs');
INSERT INTO `quetes` VALUES ('154', 'Les sbires du maître');
INSERT INTO `quetes` VALUES ('155', 'Un juge hystérique');
INSERT INTO `quetes` VALUES ('156', 'Des donjons, encore des donjons');
INSERT INTO `quetes` VALUES ('157', 'La voie du guerrier');
INSERT INTO `quetes` VALUES ('158', 'Ca est frugal, une fois');
INSERT INTO `quetes` VALUES ('163', 'Les Gobelins de la Manufacture ');
INSERT INTO `quetes` VALUES ('164', 'Bienvenue au Krazybwork saloon');
INSERT INTO `quetes` VALUES ('165', 'Bworkidais le paxifik');
INSERT INTO `quetes` VALUES ('166', 'Manque de moule');
INSERT INTO `quetes` VALUES ('167', 'Titi Gobelait le magobelin ');
INSERT INTO `quetes` VALUES ('168', 'Manque de peaux');
INSERT INTO `quetes` VALUES ('169', 'Une baguette pour Chef Bworkestre');
INSERT INTO `quetes` VALUES ('177', 'Gobmichet vibre pour Gobrose');
INSERT INTO `quetes` VALUES ('178', 'Service commandé.');
INSERT INTO `quetes` VALUES ('179', 'Par Monts et par vaux.');
INSERT INTO `quetes` VALUES ('190', 'Un décès temporaire.');
INSERT INTO `quetes` VALUES ('191', 'Oser défier un Osa.');
INSERT INTO `quetes` VALUES ('195', 'Service commandé.');
INSERT INTO `quetes` VALUES ('196', 'Service commandé.');
INSERT INTO `quetes` VALUES ('197', 'Service commandé.');
INSERT INTO `quetes` VALUES ('199', 'Les beaux arts.');
INSERT INTO `quetes` VALUES ('200', 'La complainte de Lykhen');
INSERT INTO `quetes` VALUES ('208', 'Le Guide du Roublard');
INSERT INTO `quetes` VALUES ('215', 'Emissaire du roi');
INSERT INTO `quetes` VALUES ('216', 'Info pour un vrai traître');
INSERT INTO `quetes` VALUES ('217', 'Usuwpation d\'identité ');
INSERT INTO `quetes` VALUES ('218', 'Tomber sur un bec');
INSERT INTO `quetes` VALUES ('219', 'A roublard, roublard et demi');
INSERT INTO `quetes` VALUES ('220', 'Trouble-fête');
INSERT INTO `quetes` VALUES ('221', 'Le Pwince Monseigneuw');
INSERT INTO `quetes` VALUES ('205', 'Allez, au turbin.');
INSERT INTO `quetes` VALUES ('224', 'Un mawiage pwincier');
INSERT INTO `quetes` VALUES ('226', 'Quete test');
INSERT INTO `quetes` VALUES ('229', 'Le déguisement du Koalak');
INSERT INTO `quetes` VALUES ('230', 'Le Gardien du Pont de la Mort');
INSERT INTO `quetes` VALUES ('231', 'Le nouveau monde');
INSERT INTO `quetes` VALUES ('232', 'L\'île des naufragés');
INSERT INTO `quetes` VALUES ('233', 'Le Chevalier Noir et Rose');
INSERT INTO `quetes` VALUES ('234', 'La Potion Bulbique');
INSERT INTO `quetes` VALUES ('235', 'Polka Merer a besoin de vous');
INSERT INTO `quetes` VALUES ('236', 'Paulette Pain-bèche la boulangère');
INSERT INTO `quetes` VALUES ('237', 'Le fils caché ');
INSERT INTO `quetes` VALUES ('238', 'La femme perdue');
INSERT INTO `quetes` VALUES ('239', 'Scaéroplane à très grande vitesse');
INSERT INTO `quetes` VALUES ('240', 'Un autre moyen de transport');
INSERT INTO `quetes` VALUES ('241', 'Les Chasses de Crocodaille Dandi');
INSERT INTO `quetes` VALUES ('242', 'La vengeance du Kito');
INSERT INTO `quetes` VALUES ('243', 'La vengeance de Peggy la Porkass');
INSERT INTO `quetes` VALUES ('245', 'La faux Maudite');
INSERT INTO `quetes` VALUES ('253', 'Cambriolage.');
INSERT INTO `quetes` VALUES ('260', 'A l\'endroit, à l\'envers.');
INSERT INTO `quetes` VALUES ('263', 'Bouc à misère.');
INSERT INTO `quetes` VALUES ('266', 'La capture.');
INSERT INTO `quetes` VALUES ('286', 'Ambition ambigüe.');
INSERT INTO `quetes` VALUES ('435', 'Apprentissage : Disciple de Silvosse');
INSERT INTO `quetes` VALUES ('414', 'A la rescousse d\'un incapable.');
INSERT INTO `quetes` VALUES ('449', 'Chasseur de têtes.');
INSERT INTO `quetes` VALUES ('489', 'Bien débuter');
INSERT INTO `quetes` VALUES ('493', 'Des racines et des ouailles.');
INSERT INTO `quetes` VALUES ('523', 'Joyeux Nowel.');
INSERT INTO `quetes` VALUES ('490', 'Ne pas traduire');
INSERT INTO `quetes` VALUES ('471', 'Dévotion.');
INSERT INTO `quetes` VALUES ('442', 'Bonta a vraiment besoin de vous !');
INSERT INTO `quetes` VALUES ('22', 'La Quête Du Pabo');
INSERT INTO `quetes` VALUES ('413', 'Au combat !');
INSERT INTO `quetes` VALUES ('27', '(next)Maladie chronique');
INSERT INTO `quetes` VALUES ('264', 'Flagrant délire.');
INSERT INTO `quetes` VALUES ('311', 'Les ordres sont-ils les ordres ?');
INSERT INTO `quetes` VALUES ('52', 'Aiguilles de rats...');
INSERT INTO `quetes` VALUES ('32', 'Retrouver Qil Bil');
INSERT INTO `quetes` VALUES ('441', 'Brâkmar a vraiment besoin de vous !');
INSERT INTO `quetes` VALUES ('3', 'La discorde végétale');
INSERT INTO `quetes` VALUES ('19', '(next) La Maison Fantome');
INSERT INTO `quetes` VALUES ('12', '(next) Livraison de Pizaille');
INSERT INTO `quetes` VALUES ('51', 'Dératisation !');
INSERT INTO `quetes` VALUES ('49', 'Plus de Nageant-infecte-cieux !');
INSERT INTO `quetes` VALUES ('8', 'Du sang froid !');
INSERT INTO `quetes` VALUES ('16', 'Et une baguette de Dzibi, une !');
INSERT INTO `quetes` VALUES ('42', 'Fecaffe à mon troupeau');
INSERT INTO `quetes` VALUES ('97', 'Pandala : Sa Déesse...');
INSERT INTO `quetes` VALUES ('143', 'Allez hue !');
INSERT INTO `quetes` VALUES ('28', 'Le monocle de Wally');
INSERT INTO `quetes` VALUES ('629', 'Mel au drame.');
INSERT INTO `quetes` VALUES ('628', 'Mel odieuse.');