INSERT INTO `npc_name` VALUES ('549', '???');
INSERT INTO `npc_name` VALUES ('1277', '???');
INSERT INTO `npc_name` VALUES ('63', 'Abely Bobeule');
INSERT INTO `npc_name` VALUES ('497', 'Abrazelon Sixgriffe');
INSERT INTO `npc_name` VALUES ('729', 'Acidrik Fenlapanse');
INSERT INTO `npc_name` VALUES ('686', 'Aermyne \'Braco\' Scalptaras');
INSERT INTO `npc_name` VALUES ('115', 'Aga Dou');
INSERT INTO `npc_name` VALUES ('980', 'Agent de Brâkmar');
INSERT INTO `npc_name` VALUES ('59', 'Agrid Shakoku');
INSERT INTO `npc_name` VALUES ('601', 'Ahenn Peuh');
INSERT INTO `npc_name` VALUES ('458', 'Aida');
INSERT INTO `npc_name` VALUES ('308', 'Aigurraf le Greffier');
INSERT INTO `npc_name` VALUES ('306', 'Ala Raine');
INSERT INTO `npc_name` VALUES ('900', 'Al Blourrad');
INSERT INTO `npc_name` VALUES ('328', 'Aldir Atolmond');
INSERT INTO `npc_name` VALUES ('93', 'Ale One');
INSERT INTO `npc_name` VALUES ('522', 'Al Etsop');
INSERT INTO `npc_name` VALUES ('122', 'Ali Akelle');
INSERT INTO `npc_name` VALUES ('1224', 'Ali Macbeth');
INSERT INTO `npc_name` VALUES ('467', 'Alit Elfminate');
INSERT INTO `npc_name` VALUES ('749', 'Alka Traz');
INSERT INTO `npc_name` VALUES ('95', 'Allen Déchakal');
INSERT INTO `npc_name` VALUES ('262', 'Allen Tokar');
INSERT INTO `npc_name` VALUES ('471', 'Allisteria');
INSERT INTO `npc_name` VALUES ('171', 'Al Okab');
INSERT INTO `npc_name` VALUES ('172', 'Alshain');
INSERT INTO `npc_name` VALUES ('177', 'Altaïr');
INSERT INTO `npc_name` VALUES ('174', 'Altaïr');
INSERT INTO `npc_name` VALUES ('875', 'Amaché Ganymede');
INSERT INTO `npc_name` VALUES ('180', 'Amayiro');
INSERT INTO `npc_name` VALUES ('620', 'Amayiro (MAJ)');
INSERT INTO `npc_name` VALUES ('1043', 'Âme de Terra Tibya');
INSERT INTO `npc_name` VALUES ('37', 'Amine');
INSERT INTO `npc_name` VALUES ('316', 'Angelo Bolle');
INSERT INTO `npc_name` VALUES ('220', 'Anik Mech');
INSERT INTO `npc_name` VALUES ('874', 'Anta Brok');
INSERT INTO `npc_name` VALUES ('543', 'Ant Emicheun');
INSERT INTO `npc_name` VALUES ('818', 'Aperirel');
INSERT INTO `npc_name` VALUES ('975', 'Archère équipée');
INSERT INTO `npc_name` VALUES ('877', 'Arevnyr Ganymede');
INSERT INTO `npc_name` VALUES ('89', 'Aria Knofob');
INSERT INTO `npc_name` VALUES ('847', 'Arietta Fiole');
INSERT INTO `npc_name` VALUES ('112', 'Ariz');
INSERT INTO `npc_name` VALUES ('1116', 'Arlette Ba');
INSERT INTO `npc_name` VALUES ('193', 'Arone');
INSERT INTO `npc_name` VALUES ('733', 'Arpagnagrobis');
INSERT INTO `npc_name` VALUES ('278', 'Artok');
INSERT INTO `npc_name` VALUES ('119', 'Assistant d\'Otomaï');
INSERT INTO `npc_name` VALUES ('1077', 'Assistante d\'Otomaï');
INSERT INTO `npc_name` VALUES ('630', 'Assistant Shaman');
INSERT INTO `npc_name` VALUES ('876', 'Atapé Ganymede');
INSERT INTO `npc_name` VALUES ('888', 'Avaulé Ganymede ');
INSERT INTO `npc_name` VALUES ('878', 'Aymé Tairnaile');
INSERT INTO `npc_name` VALUES ('52', 'Azra Lazarus');
INSERT INTO `npc_name` VALUES ('266', 'Baal O\'Char');
INSERT INTO `npc_name` VALUES ('727', 'Badufron chef mercenaire');
INSERT INTO `npc_name` VALUES ('828', 'Bandit de gras chemin');
INSERT INTO `npc_name` VALUES ('1106', 'Bandit des plaines');
INSERT INTO `npc_name` VALUES ('100', 'Banquier');
INSERT INTO `npc_name` VALUES ('1228', 'Baramine');
INSERT INTO `npc_name` VALUES ('670', 'Bardawa le Marchand');
INSERT INTO `npc_name` VALUES ('658', 'Bawler');
INSERT INTO `npc_name` VALUES ('661', 'Bazarwa la Marchande');
INSERT INTO `npc_name` VALUES ('399', 'Belguel Cul-Talon');
INSERT INTO `npc_name` VALUES ('96', 'Bellus Sel');
INSERT INTO `npc_name` VALUES ('170', 'Benn Zin');
INSERT INTO `npc_name` VALUES ('950', 'Berkzoy');
INSERT INTO `npc_name` VALUES ('439', 'Bernardo Peule');
INSERT INTO `npc_name` VALUES ('709', 'Berthawa');
INSERT INTO `npc_name` VALUES ('300', 'Bhan Laka');
INSERT INTO `npc_name` VALUES ('1034', 'Bibiblop');
INSERT INTO `npc_name` VALUES ('767', 'Bibliothécaire');
INSERT INTO `npc_name` VALUES ('235', 'Bill Iédebar');
INSERT INTO `npc_name` VALUES ('663', 'Binzawa le Marchand');
INSERT INTO `npc_name` VALUES ('577', 'Bish Fone');
INSERT INTO `npc_name` VALUES ('614', 'Blouh Béryl');
INSERT INTO `npc_name` VALUES ('669', 'Bobardawa le Marchand');
INSERT INTO `npc_name` VALUES ('906', 'Bob Lenald');
INSERT INTO `npc_name` VALUES ('1230', 'Bob l\'Enutrof');
INSERT INTO `npc_name` VALUES ('168', 'Boff Chalon');
INSERT INTO `npc_name` VALUES ('117', 'Bolzano Vieilletrasse');
INSERT INTO `npc_name` VALUES ('82', 'Boude Spenssour');
INSERT INTO `npc_name` VALUES ('411', 'Bouftocornus');
INSERT INTO `npc_name` VALUES ('530', 'Bouftou apprivoisé');
INSERT INTO `npc_name` VALUES ('533', 'Bouftou apprivoisé');
INSERT INTO `npc_name` VALUES ('532', 'Bouftou apprivoisé');
INSERT INTO `npc_name` VALUES ('529', 'Bouftou apprivoisé');
INSERT INTO `npc_name` VALUES ('531', 'Bouftou apprivoisé');
INSERT INTO `npc_name` VALUES ('810', 'Bouftouteater');
INSERT INTO `npc_name` VALUES ('279', 'Boulor');
INSERT INTO `npc_name` VALUES ('1054', 'Boumawa');
INSERT INTO `npc_name` VALUES ('271', 'Bout d\'chair ');
INSERT INTO `npc_name` VALUES ('645', 'Bouwada');
INSERT INTO `npc_name` VALUES ('57', 'Bowisse');
INSERT INTO `npc_name` VALUES ('775', 'Bowork');
INSERT INTO `npc_name` VALUES ('682', 'Boyrun Pticou');
INSERT INTO `npc_name` VALUES ('816', 'Bricky Brock');
INSERT INTO `npc_name` VALUES ('436', 'Brigitebardo Peule');
INSERT INTO `npc_name` VALUES ('379', 'Brik Enbroc');
INSERT INTO `npc_name` VALUES ('616', 'Brookite Pyrite');
INSERT INTO `npc_name` VALUES ('312', 'Bruli Ounim');
INSERT INTO `npc_name` VALUES ('512', 'Brumen Tinctorias');
INSERT INTO `npc_name` VALUES ('881', 'Bûcheron d\'Incarnam');
INSERT INTO `npc_name` VALUES ('701', 'Bulbig');
INSERT INTO `npc_name` VALUES ('401', 'Bullie Duble ');
INSERT INTO `npc_name` VALUES ('672', 'Bushido Peule');
INSERT INTO `npc_name` VALUES ('1102', 'Bwak de feu');
INSERT INTO `npc_name` VALUES ('703', 'Bwon Bargwain');
INSERT INTO `npc_name` VALUES ('840', 'Bworkcelhaine');
INSERT INTO `npc_name` VALUES ('851', 'Bworkcine');
INSERT INTO `npc_name` VALUES ('842', 'Bworkepik');
INSERT INTO `npc_name` VALUES ('832', 'Bworkidais le paxifik');
INSERT INTO `npc_name` VALUES ('712', 'Bworkie');
INSERT INTO `npc_name` VALUES ('413', 'Bworkitus');
INSERT INTO `npc_name` VALUES ('833', 'Bworknroll');
INSERT INTO `npc_name` VALUES ('1456', 'Cage');
INSERT INTO `npc_name` VALUES ('1457', 'Cage vide');
INSERT INTO `npc_name` VALUES ('671', 'Camelotawa le Marchand');
INSERT INTO `npc_name` VALUES ('215', 'Capitaine Alrok');
INSERT INTO `npc_name` VALUES ('668', 'Capitaine Banwana');
INSERT INTO `npc_name` VALUES ('854', 'Capitaine des Kerubims');
INSERT INTO `npc_name` VALUES ('330', 'Capitaine Essacarf');
INSERT INTO `npc_name` VALUES ('942', 'Capitaine Flams');
INSERT INTO `npc_name` VALUES ('798', 'Capitaine Igloute');
INSERT INTO `npc_name` VALUES ('336', 'Capitaine Koda');
INSERT INTO `npc_name` VALUES ('925', 'Capitaine Kradoc');
INSERT INTO `npc_name` VALUES ('257', 'Capitaine Malfe');
INSERT INTO `npc_name` VALUES ('55', 'Captain Iglout');
INSERT INTO `npc_name` VALUES ('804', 'Captain Starky');
INSERT INTO `npc_name` VALUES ('61', 'Casper Van Brushing');
INSERT INTO `npc_name` VALUES ('946', 'Chachka');
INSERT INTO `npc_name` VALUES ('368', 'Chafer Archer');
INSERT INTO `npc_name` VALUES ('175', 'Chaferfu');
INSERT INTO `npc_name` VALUES ('1284', 'Chafer Maudit');
INSERT INTO `npc_name` VALUES ('384', 'Chaki Triss');
INSERT INTO `npc_name` VALUES ('23', 'Charlotte');
INSERT INTO `npc_name` VALUES ('882', 'Chasseur d\'Incarnam');
INSERT INTO `npc_name` VALUES ('844', 'Chef Bworkestre');
INSERT INTO `npc_name` VALUES ('968', 'Chef des espions');
INSERT INTO `npc_name` VALUES ('1129', 'Chef des renégats bontariens');
INSERT INTO `npc_name` VALUES ('1094', 'Chef des voleurs');
INSERT INTO `npc_name` VALUES ('1101', 'Chef du convoi');
INSERT INTO `npc_name` VALUES ('338', 'Chef Milicien');
INSERT INTO `npc_name` VALUES ('638', 'Chef Pandikaze');
INSERT INTO `npc_name` VALUES ('164', 'Cherlook Holmus');
INSERT INTO `npc_name` VALUES ('363', 'Chevalier Fougarde');
INSERT INTO `npc_name` VALUES ('311', 'Chevalier Hertuen');
INSERT INTO `npc_name` VALUES ('222', 'Chevalier Neuthr');
INSERT INTO `npc_name` VALUES ('334', 'Chevalier Nogard');
INSERT INTO `npc_name` VALUES ('927', 'Chevalier Noir et Rose');
INSERT INTO `npc_name` VALUES ('596', 'Chipo Atufe');
INSERT INTO `npc_name` VALUES ('815', 'Chris de Naire');
INSERT INTO `npc_name` VALUES ('599', 'Cirle Drawde');
INSERT INTO `npc_name` VALUES ('199', 'Clara Daule');
INSERT INTO `npc_name` VALUES ('958', 'Classman');
INSERT INTO `npc_name` VALUES ('485', 'Clint Pot');
INSERT INTO `npc_name` VALUES ('493', 'Clyde Peus');
INSERT INTO `npc_name` VALUES ('1281', 'Coffre en ambre');
INSERT INTO `npc_name` VALUES ('1280', 'Coffre en emeraude');
INSERT INTO `npc_name` VALUES ('1278', 'Coffre en rubis');
INSERT INTO `npc_name` VALUES ('1279', 'Coffre en saphir');
INSERT INTO `npc_name` VALUES ('333', 'Colonel Lyeno');
INSERT INTO `npc_name` VALUES ('973', 'Commandant bontarien Kad');
INSERT INTO `npc_name` VALUES ('236', 'Connie Vini');
INSERT INTO `npc_name` VALUES ('628', 'Conseiller Anshwa');
INSERT INTO `npc_name` VALUES ('625', 'Conseiller Boyowa');
INSERT INTO `npc_name` VALUES ('626', 'Conseiller Legawa');
INSERT INTO `npc_name` VALUES ('629', 'Conseiller Nougwa');
INSERT INTO `npc_name` VALUES ('627', 'Conseiller Rinsdwa');
INSERT INTO `npc_name` VALUES ('893', 'Conseiller Yse Vewybad');
INSERT INTO `npc_name` VALUES ('849', 'Contremaître Ikul');
INSERT INTO `npc_name` VALUES ('1111', 'Corbac');
INSERT INTO `npc_name` VALUES ('666', 'Corserawa le Marchand');
INSERT INTO `npc_name` VALUES ('352', 'Coupable I');
INSERT INTO `npc_name` VALUES ('353', 'Coupable II');
INSERT INTO `npc_name` VALUES ('354', 'Coupable III');
INSERT INTO `npc_name` VALUES ('959', 'Craqueleur Poli Poli');
INSERT INTO `npc_name` VALUES ('937', 'Crocodaille Dandi');
INSERT INTO `npc_name` VALUES ('802', 'Dainde Porteplume');
INSERT INTO `npc_name` VALUES ('185', 'Dame Cloude');
INSERT INTO `npc_name` VALUES ('903', 'Dame de la cour');
INSERT INTO `npc_name` VALUES ('318', 'Danathor');
INSERT INTO `npc_name` VALUES ('265', 'Dante Sion');
INSERT INTO `npc_name` VALUES ('673', 'Dark Vlad');
INSERT INTO `npc_name` VALUES ('87', 'Ded Aléïcar');
INSERT INTO `npc_name` VALUES ('1235', 'Dédé Toure Neman');
INSERT INTO `npc_name` VALUES ('747', 'Degui Quetiristou');
INSERT INTO `npc_name` VALUES ('385', 'Deneb Okab');
INSERT INTO `npc_name` VALUES ('957', 'Denis Brouillard');
INSERT INTO `npc_name` VALUES ('1051', 'Dépouille de renégat');
INSERT INTO `npc_name` VALUES ('482', 'Deudoiné');
INSERT INTO `npc_name` VALUES ('267', 'Diabalou');
INSERT INTO `npc_name` VALUES ('763', 'Diamantine');
INSERT INTO `npc_name` VALUES ('395', 'Dicenai Lond');
INSERT INTO `npc_name` VALUES ('1166', 'Dikaprio');
INSERT INTO `npc_name` VALUES ('227', 'Dike Tarak');
INSERT INTO `npc_name` VALUES ('605', 'Disciple mercenaire');
INSERT INTO `npc_name` VALUES ('607', 'Disciple Roublard');
INSERT INTO `npc_name` VALUES ('855', 'Disskray Nhin');
INSERT INTO `npc_name` VALUES ('684', 'Divad Dleifrepok');
INSERT INTO `npc_name` VALUES ('490', 'Diver Birel');
INSERT INTO `npc_name` VALUES ('105', 'Djonz');
INSERT INTO `npc_name` VALUES ('933', 'Docteur Morose');
INSERT INTO `npc_name` VALUES ('930', 'Docteur Nauh');
INSERT INTO `npc_name` VALUES ('691', 'Dollarawan Le Banquier');
INSERT INTO `npc_name` VALUES ('367', 'Domen');
INSERT INTO `npc_name` VALUES ('178', 'Don Rouann');
INSERT INTO `npc_name` VALUES ('1076', 'Doro le Blak');
INSERT INTO `npc_name` VALUES ('223', 'Doug Tulvin');
INSERT INTO `npc_name` VALUES ('414', 'Dragominotorus');
INSERT INTO `npc_name` VALUES ('1118', 'Dréna Nassema');
INSERT INTO `npc_name` VALUES ('125', 'Drogho Cralasar');
INSERT INTO `npc_name` VALUES ('679', 'Ebru Of El');
INSERT INTO `npc_name` VALUES ('1108', 'Ecaline');
INSERT INTO `npc_name` VALUES ('880', 'Ecraz Néhofite');
INSERT INTO `npc_name` VALUES ('362', 'Ecureuil ambulant');
INSERT INTO `npc_name` VALUES ('359', 'Ecureuil attachant');
INSERT INTO `npc_name` VALUES ('226', 'Ecureuil clairvoyant');
INSERT INTO `npc_name` VALUES ('373', 'Ecureuil miraculeux');
INSERT INTO `npc_name` VALUES ('360', 'Ecureuil savant');
INSERT INTO `npc_name` VALUES ('361', 'Ecureuil séduisant');
INSERT INTO `npc_name` VALUES ('736', 'Edgg Komb');
INSERT INTO `npc_name` VALUES ('440', 'Edmondo Peule');
INSERT INTO `npc_name` VALUES ('47', 'Edrige Valling');
INSERT INTO `npc_name` VALUES ('879', 'Eek Mite');
INSERT INTO `npc_name` VALUES ('388', 'Efu Irtaface');
INSERT INTO `npc_name` VALUES ('448', 'Eilof Aledec');
INSERT INTO `npc_name` VALUES ('965', 'Ekusoyk Ubnan');
INSERT INTO `npc_name` VALUES ('129', 'Eleveur de Dragoeuf');
INSERT INTO `npc_name` VALUES ('425', 'Elisa Granite');
INSERT INTO `npc_name` VALUES ('656', 'Elogio');
INSERT INTO `npc_name` VALUES ('781', 'El Scarador');
INSERT INTO `npc_name` VALUES ('426', 'Eluhise Valing');
INSERT INTO `npc_name` VALUES ('680', 'Elviana Tirips');
INSERT INTO `npc_name` VALUES ('46', 'Elya Wood');
INSERT INTO `npc_name` VALUES ('103', 'Ely Woullack');
INSERT INTO `npc_name` VALUES ('762', 'Emeraude');
INSERT INTO `npc_name` VALUES ('558', 'Emia Elliesol');
INSERT INTO `npc_name` VALUES ('432', 'Emilie Yuh');
INSERT INTO `npc_name` VALUES ('1127', 'Emma Sacre');
INSERT INTO `npc_name` VALUES ('157', 'Employé de l\'agence Touriste');
INSERT INTO `npc_name` VALUES ('284', 'Enamira');
INSERT INTO `npc_name` VALUES ('1045', 'Eni Hoube');
INSERT INTO `npc_name` VALUES ('503', 'Enileda');
INSERT INTO `npc_name` VALUES ('1119', 'Eniripsa de Brâkmar');
INSERT INTO `npc_name` VALUES ('234', 'Enoué Chupac');
INSERT INTO `npc_name` VALUES ('124', 'Eowïne Fiole');
INSERT INTO `npc_name` VALUES ('43', 'Epuop Tik');
INSERT INTO `npc_name` VALUES ('206', 'Erem Dran');
INSERT INTO `npc_name` VALUES ('1036', 'Ernesto Rouste');
INSERT INTO `npc_name` VALUES ('449', 'Erty Trapchet');
INSERT INTO `npc_name` VALUES ('979', 'Espion blessé');
INSERT INTO `npc_name` VALUES ('981', 'Espion en fuite');
INSERT INTO `npc_name` VALUES ('1047', 'Espionne Brâkmarienne');
INSERT INTO `npc_name` VALUES ('827', 'essai mineur sombre [WIP]');
INSERT INTO `npc_name` VALUES ('520', 'Essiac d\'Engrape');
INSERT INTO `npc_name` VALUES ('602', 'Esuellat');
INSERT INTO `npc_name` VALUES ('868', 'Evayée Doureve');
INSERT INTO `npc_name` VALUES ('962', 'Exoram');
INSERT INTO `npc_name` VALUES ('498', 'Fallanster');
INSERT INTO `npc_name` VALUES ('53', 'Farle Ingalsse');
INSERT INTO `npc_name` VALUES ('396', 'Faur Inkaisse');
INSERT INTO `npc_name` VALUES ('1223', 'Fée Risette');
INSERT INTO `npc_name` VALUES ('830', 'Feldz Paffe');
INSERT INTO `npc_name` VALUES ('430', 'Félénie Grismina');
INSERT INTO `npc_name` VALUES ('1232', 'Félix Nowel');
INSERT INTO `npc_name` VALUES ('406', 'Fey Gnan');
INSERT INTO `npc_name` VALUES ('766', 'Fidji Merline');
INSERT INTO `npc_name` VALUES ('40', 'Filgar Feel');
INSERT INTO `npc_name` VALUES ('188', 'Finche Aticus');
INSERT INTO `npc_name` VALUES ('631', 'Fleurawa la Marchande');
INSERT INTO `npc_name` VALUES ('415', 'Fleutus Riktus');
INSERT INTO `npc_name` VALUES ('936', 'Flip Flap');
INSERT INTO `npc_name` VALUES ('191', 'Flora Retnie');
INSERT INTO `npc_name` VALUES ('1282', 'Force Étrange');
INSERT INTO `npc_name` VALUES ('1283', 'Force Étrange');
INSERT INTO `npc_name` VALUES ('515', 'Fouduglen l\'Ecureuil');
INSERT INTO `npc_name` VALUES ('665', 'Fourbyawa le Marchand');
INSERT INTO `npc_name` VALUES ('513', 'Frakacia Leukocytine');
INSERT INTO `npc_name` VALUES ('403', 'Frank Genis');
INSERT INTO `npc_name` VALUES ('98', 'Frankie');
INSERT INTO `npc_name` VALUES ('823', 'Fred Austère');
INSERT INTO `npc_name` VALUES ('759', 'Frivolak');
INSERT INTO `npc_name` VALUES ('899', 'Frost Hize');
INSERT INTO `npc_name` VALUES ('258', 'Fryda Griffe-de-la-Nuit');
INSERT INTO `npc_name` VALUES ('380', 'Frye Handiz');
INSERT INTO `npc_name` VALUES ('285', 'Fulsura');
INSERT INTO `npc_name` VALUES ('456', 'Fuu Yie');
INSERT INTO `npc_name` VALUES ('784', 'Fwoued');
INSERT INTO `npc_name` VALUES ('225', 'Gaï Tane');
INSERT INTO `npc_name` VALUES ('213', 'Galde Avout');
INSERT INTO `npc_name` VALUES ('865', 'Galileo Maginifico');
INSERT INTO `npc_name` VALUES ('378', 'Ganymède');
INSERT INTO `npc_name` VALUES ('382', 'Ganymède');
INSERT INTO `npc_name` VALUES ('643', 'Garde Aerdala');
INSERT INTO `npc_name` VALUES ('350', 'Garde Aybou Ganslante');
INSERT INTO `npc_name` VALUES ('621', 'Garde Chopynwa');
INSERT INTO `npc_name` VALUES ('1114', 'Garde de convoi');
INSERT INTO `npc_name` VALUES ('1130', 'Garde déguisé');
INSERT INTO `npc_name` VALUES ('1112', 'Garde de la tour');
INSERT INTO `npc_name` VALUES ('349', 'Garde Herviss Ganslante');
INSERT INTO `npc_name` VALUES ('1231', 'Garde Heury');
INSERT INTO `npc_name` VALUES ('913', 'Garde Montay');
INSERT INTO `npc_name` VALUES ('348', 'Garde Pritt Ganslante');
INSERT INTO `npc_name` VALUES ('676', 'Garde Toide Grocwayo');
INSERT INTO `npc_name` VALUES ('675', 'Garde Tono Portwa');
INSERT INTO `npc_name` VALUES ('700', 'Garde Uboi Porefeu');
INSERT INTO `npc_name` VALUES ('606', 'Gardien');
INSERT INTO `npc_name` VALUES ('358', 'Gardien Ace Bruth');
INSERT INTO `npc_name` VALUES ('799', 'Gardien du donjon des rats de Bonta');
INSERT INTO `npc_name` VALUES ('800', 'Gardien du donjon des rats de Brâkmar');
INSERT INTO `npc_name` VALUES ('78', 'Gardien du Kanojedo');
INSERT INTO `npc_name` VALUES ('928', 'Gardien du Pont de la Mort');
INSERT INTO `npc_name` VALUES ('1097', 'Gardien du puits');
INSERT INTO `npc_name` VALUES ('754', 'Gardien Koalak');
INSERT INTO `npc_name` VALUES ('505', 'Gasdaure');
INSERT INTO `npc_name` VALUES ('147', 'Gawde Wabbit');
INSERT INTO `npc_name` VALUES ('148', 'Gawdien Dofus');
INSERT INTO `npc_name` VALUES ('149', 'Gawdien Dofus');
INSERT INTO `npc_name` VALUES ('540', 'Gazogen');
INSERT INTO `npc_name` VALUES ('542', 'Gazoline');
INSERT INTO `npc_name` VALUES ('538', 'Gazpacho');
INSERT INTO `npc_name` VALUES ('541', 'Gazteropod');
INSERT INTO `npc_name` VALUES ('374', 'Gelée Royale Bleue');
INSERT INTO `npc_name` VALUES ('375', 'Gelée Royale Citron');
INSERT INTO `npc_name` VALUES ('376', 'Gelée Royale Fraise');
INSERT INTO `npc_name` VALUES ('377', 'Gelée Royale Menthe');
INSERT INTO `npc_name` VALUES ('746', 'Gemfé Labelle');
INSERT INTO `npc_name` VALUES ('653', 'Gèmpa');
INSERT INTO `npc_name` VALUES ('652', 'Gèmpa Metoasa');
INSERT INTO `npc_name` VALUES ('1093', 'Geôlier de Sabine');
INSERT INTO `npc_name` VALUES ('785', 'George Cash');
INSERT INTO `npc_name` VALUES ('209', 'Gigi');
INSERT INTO `npc_name` VALUES ('864', 'Gilles Caper');
INSERT INTO `npc_name` VALUES ('383', 'Girle Pylote');
INSERT INTO `npc_name` VALUES ('1453', 'Gladiatroc');
INSERT INTO `npc_name` VALUES ('834', 'Gobatchef');
INSERT INTO `npc_name` VALUES ('337', 'Gobelin');
INSERT INTO `npc_name` VALUES ('836', 'Gobiere Trokeur');
INSERT INTO `npc_name` VALUES ('853', 'Gobmichet');
INSERT INTO `npc_name` VALUES ('845', 'Gobriel');
INSERT INTO `npc_name` VALUES ('852', 'Gobrose');
INSERT INTO `npc_name` VALUES ('332', 'Goldo Arak');
INSERT INTO `npc_name` VALUES ('416', 'Gorko Casku');
INSERT INTO `npc_name` VALUES ('1218', 'Goultard');
INSERT INTO `npc_name` VALUES ('1269', 'Goultard');
INSERT INTO `npc_name` VALUES ('1216', 'Goultard');
INSERT INTO `npc_name` VALUES ('217', 'Grace Malcean');
INSERT INTO `npc_name` VALUES ('62', 'Graham Finame');
INSERT INTO `npc_name` VALUES ('477', 'Grand-mère');
INSERT INTO `npc_name` VALUES ('340', 'Greg Aougos');
INSERT INTO `npc_name` VALUES ('132', 'Gregor Mendal');
INSERT INTO `npc_name` VALUES ('1110', 'Grimpill');
INSERT INTO `npc_name` VALUES ('302', 'Gringa');
INSERT INTO `npc_name` VALUES ('304', 'Gringi');
INSERT INTO `npc_name` VALUES ('301', 'Gringo');
INSERT INTO `npc_name` VALUES ('303', 'Gringu');
INSERT INTO `npc_name` VALUES ('80', 'Grizmine');
INSERT INTO `npc_name` VALUES ('872', 'Grobid Le Vétéran Kerubim');
INSERT INTO `npc_name` VALUES ('151', 'Gropinson Cruaulé');
INSERT INTO `npc_name` VALUES ('461', 'Gros piou');
INSERT INTO `npc_name` VALUES ('751', 'Guan Tanamault');
INSERT INTO `npc_name` VALUES ('744', 'Guedin Loursgro');
INSERT INTO `npc_name` VALUES ('255', 'Guerrier Bishom Pot');
INSERT INTO `npc_name` VALUES ('246', 'Guerrier Brank Thoof');
INSERT INTO `npc_name` VALUES ('251', 'Guerrier Haco Norss');
INSERT INTO `npc_name` VALUES ('250', 'Guerrier Jack Rottance');
INSERT INTO `npc_name` VALUES ('249', 'Guerrier Kad Maxy');
INSERT INTO `npc_name` VALUES ('253', 'Guerrier Nager Nacmeil');
INSERT INTO `npc_name` VALUES ('247', 'Guerrier Seta Bnamron');
INSERT INTO `npc_name` VALUES ('254', 'Guerrier Sivart Bicelk');
INSERT INTO `npc_name` VALUES ('248', 'Guerrier Tink Berval');
INSERT INTO `npc_name` VALUES ('252', 'Guerrier Xale DuGros');
INSERT INTO `npc_name` VALUES ('1113', 'Gueurle');
INSERT INTO `npc_name` VALUES ('370', 'Guf Ruheu');
INSERT INTO `npc_name` VALUES ('609', 'Guy San Nolan');
INSERT INTO `npc_name` VALUES ('545', 'Gwenolaz Barnumuze');
INSERT INTO `npc_name` VALUES ('281', 'Gymy Ro');
INSERT INTO `npc_name` VALUES ('890', 'Habitué de la taverne');
INSERT INTO `npc_name` VALUES ('435', 'Haïkido Peule');
INSERT INTO `npc_name` VALUES ('779', 'Halda Moccione');
INSERT INTO `npc_name` VALUES ('58', 'Hanniboul Smisse');
INSERT INTO `npc_name` VALUES ('740', 'Haraquiri');
INSERT INTO `npc_name` VALUES ('60', 'Harrys Corb');
INSERT INTO `npc_name` VALUES ('127', 'Harry Stote');
INSERT INTO `npc_name` VALUES ('795', 'Hector Nowel');
INSERT INTO `npc_name` VALUES ('955', 'Hélène Meyer');
INSERT INTO `npc_name` VALUES ('176', 'Hel Munster');
INSERT INTO `npc_name` VALUES ('446', 'Henual');
INSERT INTO `npc_name` VALUES ('646', 'Henual');
INSERT INTO `npc_name` VALUES ('655', 'Henual');
INSERT INTO `npc_name` VALUES ('782', 'Herman Capotie');
INSERT INTO `npc_name` VALUES ('192', 'Hersa Griffe Sombre ');
INSERT INTO `npc_name` VALUES ('214', 'Hete Renelt');
INSERT INTO `npc_name` VALUES ('369', 'Heticili Ufot ');
INSERT INTO `npc_name` VALUES ('118', 'Heûl Leise');
INSERT INTO `npc_name` VALUES ('1099', 'Highlambert');
INSERT INTO `npc_name` VALUES ('398', 'Hinss Hairt');
INSERT INTO `npc_name` VALUES ('429', 'Hirpine Fécalamité');
INSERT INTO `npc_name` VALUES ('331', 'Houé Dapyus');
INSERT INTO `npc_name` VALUES ('92', 'Hourax Hipipe');
INSERT INTO `npc_name` VALUES ('489', 'Howard le Simaisrien');
INSERT INTO `npc_name` VALUES ('79', 'Hugo Bélo');
INSERT INTO `npc_name` VALUES ('314', 'Huta Wouite');
INSERT INTO `npc_name` VALUES ('290', 'Iakos');
INSERT INTO `npc_name` VALUES ('325', 'Ichassi Djaul');
INSERT INTO `npc_name` VALUES ('1023', 'Ilyzaelle[wip]');
INSERT INTO `npc_name` VALUES ('897', 'Intendant San Lavalss');
INSERT INTO `npc_name` VALUES ('487', 'Iolo Enchoua');
INSERT INTO `npc_name` VALUES ('982', 'Iop en cape brâkmarienne');
INSERT INTO `npc_name` VALUES ('677', 'Ipatsu Debanbwa');
INSERT INTO `npc_name` VALUES ('156', 'Issé Heau');
INSERT INTO `npc_name` VALUES ('1165', 'Iturik');
INSERT INTO `npc_name` VALUES ('243', 'Ivrogne anonyme');
INSERT INTO `npc_name` VALUES ('317', 'Ixa Mustam');
INSERT INTO `npc_name` VALUES ('932', 'Jean Nauh');
INSERT INTO `npc_name` VALUES ('934', 'Jeanne Morose');
INSERT INTO `npc_name` VALUES ('769', 'Jean-Sol Patre');
INSERT INTO `npc_name` VALUES ('305', 'Jerhyn Gholein');
INSERT INTO `npc_name` VALUES ('202', 'Jett Marte');
INSERT INTO `npc_name` VALUES ('323', 'Jiaye Djaul');
INSERT INTO `npc_name` VALUES ('1120', 'Jibworknouille');
INSERT INTO `npc_name` VALUES ('846', 'Jicé Aouaire');
INSERT INTO `npc_name` VALUES ('476', 'Jim Fleps');
INSERT INTO `npc_name` VALUES ('114', 'Jimmy Rasta');
INSERT INTO `npc_name` VALUES ('1140', 'Jissey Pandamme');
INSERT INTO `npc_name` VALUES ('949', 'Jock');
INSERT INTO `npc_name` VALUES ('481', 'Joe Pierlivet');
INSERT INTO `npc_name` VALUES ('824', 'Jorg Dy');
INSERT INTO `npc_name` VALUES ('797', 'Josette Taplane');
INSERT INTO `npc_name` VALUES ('433', 'Juhdo Peule');
INSERT INTO `npc_name` VALUES ('310', 'Kaffra Kyper');
INSERT INTO `npc_name` VALUES ('758', 'Kakolak');
INSERT INTO `npc_name` VALUES ('817', 'Kal Vissi');
INSERT INTO `npc_name` VALUES ('594', 'Kana Petch');
INSERT INTO `npc_name` VALUES ('167', 'Kande Boffler');
INSERT INTO `npc_name` VALUES ('155', 'Kanniboul cuisinier');
INSERT INTO `npc_name` VALUES ('159', 'Kanniboul masque');
INSERT INTO `npc_name` VALUES ('1012', 'Kapi Taigne');
INSERT INTO `npc_name` VALUES ('161', 'Kara Hibe');
INSERT INTO `npc_name` VALUES ('97', 'Karim Katékit');
INSERT INTO `npc_name` VALUES ('739', 'Kartier Tremai');
INSERT INTO `npc_name` VALUES ('1109', 'Kate Woumane');
INSERT INTO `npc_name` VALUES ('410', 'Ka Tuor');
INSERT INTO `npc_name` VALUES ('230', 'Kaze koule');
INSERT INTO `npc_name` VALUES ('778', 'Kazy Ingalsse');
INSERT INTO `npc_name` VALUES ('261', 'Kazzy Duno');
INSERT INTO `npc_name` VALUES ('104', 'Keck Auprune');
INSERT INTO `npc_name` VALUES ('51', 'Kelog Korflex');
INSERT INTO `npc_name` VALUES ('615', 'Kernite');
INSERT INTO `npc_name` VALUES ('154', 'Kib Roche');
INSERT INTO `npc_name` VALUES ('444', 'Kib Roche');
INSERT INTO `npc_name` VALUES ('956', 'Kimiya');
INSERT INTO `npc_name` VALUES ('939', 'Kito');
INSERT INTO `npc_name` VALUES ('771', 'Klako');
INSERT INTO `npc_name` VALUES ('1163', 'Klik Klak');
INSERT INTO `npc_name` VALUES ('808', 'Koka Dekolak');
INSERT INTO `npc_name` VALUES ('288', 'Koli');
INSERT INTO `npc_name` VALUES ('938', 'Kolibrie');
INSERT INTO `npc_name` VALUES ('256', 'Kosuke Ichazum');
INSERT INTO `npc_name` VALUES ('755', 'Koulosse');
INSERT INTO `npc_name` VALUES ('777', 'Kourk Ingalsse');
INSERT INTO `npc_name` VALUES ('121', 'Koussein Trengon');
INSERT INTO `npc_name` VALUES ('321', 'Krachan Porterr');
INSERT INTO `npc_name` VALUES ('772', 'Krakotte');
INSERT INTO `npc_name` VALUES ('831', 'Krazybwork');
INSERT INTO `npc_name` VALUES ('400', 'Krip Soue');
INSERT INTO `npc_name` VALUES ('322', 'Kro Burk');
INSERT INTO `npc_name` VALUES ('954', 'Kroula');
INSERT INTO `npc_name` VALUES ('608', 'Krowbe Jondon ');
INSERT INTO `npc_name` VALUES ('1008', 'Ku\'Tan[wip]');
INSERT INTO `npc_name` VALUES ('94', 'Kwaker Vans');
INSERT INTO `npc_name` VALUES ('324', 'Kwoker Djaul');
INSERT INTO `npc_name` VALUES ('947', 'Lack');
INSERT INTO `npc_name` VALUES ('1229', 'Laforay');
INSERT INTO `npc_name` VALUES ('1135', 'La Gonflante');
INSERT INTO `npc_name` VALUES ('1452', 'Lainu Prof');
INSERT INTO `npc_name` VALUES ('649', 'Lanma');
INSERT INTO `npc_name` VALUES ('88', 'Lanseuft de Troille');
INSERT INTO `npc_name` VALUES ('263', 'Lansy Odsson');
INSERT INTO `npc_name` VALUES ('99', 'Lara Soft');
INSERT INTO `npc_name` VALUES ('207', 'Larik Oubiac');
INSERT INTO `npc_name` VALUES ('201', 'Larry Poller');
INSERT INTO `npc_name` VALUES ('600', 'Latem Sa');
INSERT INTO `npc_name` VALUES ('35', 'Laura Soho');
INSERT INTO `npc_name` VALUES ('871', 'Laura Thée');
INSERT INTO `npc_name` VALUES ('200', 'Layol Nidalap ');
INSERT INTO `npc_name` VALUES ('683', 'Ledrob Terceséc');
INSERT INTO `npc_name` VALUES ('106', 'Lee Aibig');
INSERT INTO `npc_name` VALUES ('632', 'Le Grandapan');
INSERT INTO `npc_name` VALUES ('1103', 'Lelievwe Pâle Pitane');
INSERT INTO `npc_name` VALUES ('813', 'Le maître des clefs');
INSERT INTO `npc_name` VALUES ('145', 'Lenald des Temps Anciens');
INSERT INTO `npc_name` VALUES ('504', 'Leon Edehcub');
INSERT INTO `npc_name` VALUES ('197', 'Leonzi Trool');
INSERT INTO `npc_name` VALUES ('501', 'Le Remplisseur');
INSERT INTO `npc_name` VALUES ('1266', 'Léthaline Sigisbul [wip]');
INSERT INTO `npc_name` VALUES ('657', 'Leurne');
INSERT INTO `npc_name` VALUES ('140', 'Lilou la Lenald');
INSERT INTO `npc_name` VALUES ('134', 'Lily');
INSERT INTO `npc_name` VALUES ('136', 'Lily');
INSERT INTO `npc_name` VALUES ('422', 'Limine Bryone');
INSERT INTO `npc_name` VALUES ('1037', 'Lina Vortald');
INSERT INTO `npc_name` VALUES ('81', 'Linda Malibou');
INSERT INTO `npc_name` VALUES ('765', 'Liroye Merline');
INSERT INTO `npc_name` VALUES ('431', 'Lisa Modas');
INSERT INTO `npc_name` VALUES ('460', 'Locette Lurnbell');
INSERT INTO `npc_name` VALUES ('142', 'Logel le Lenald');
INSERT INTO `npc_name` VALUES ('139', 'Logel le Lenald');
INSERT INTO `npc_name` VALUES ('412', 'Longibouftus');
INSERT INTO `npc_name` VALUES ('101', 'Loopine');
INSERT INTO `npc_name` VALUES ('783', 'Lorkos');
INSERT INTO `npc_name` VALUES ('454', 'Louc Drif');
INSERT INTO `npc_name` VALUES ('667', 'Loudmerawa le Marin');
INSERT INTO `npc_name` VALUES ('107', 'Lou Pachoups');
INSERT INTO `npc_name` VALUES ('524', 'Louse Degraine');
INSERT INTO `npc_name` VALUES ('750', 'Luki Loushiano');
INSERT INTO `npc_name` VALUES ('891', 'Lykhen Lesurviven');
INSERT INTO `npc_name` VALUES ('1048', 'Mac Ronald');
INSERT INTO `npc_name` VALUES ('820', 'Madame El');
INSERT INTO `npc_name` VALUES ('726', 'Mage Ax ');
INSERT INTO `npc_name` VALUES ('776', 'Magnus Magus');
INSERT INTO `npc_name` VALUES ('642', 'Maître d\'Aerdala');
INSERT INTO `npc_name` VALUES ('634', 'Maître d\'Akwadala');
INSERT INTO `npc_name` VALUES ('636', 'Maître de Feudala');
INSERT INTO `npc_name` VALUES ('786', 'Maître des clés');
INSERT INTO `npc_name` VALUES ('641', 'Maître de Terrdala');
INSERT INTO `npc_name` VALUES ('690', 'Maître Djakky Chwan');
INSERT INTO `npc_name` VALUES ('664', 'Maître du Pandawushu');
INSERT INTO `npc_name` VALUES ('757', 'Maître Koalak');
INSERT INTO `npc_name` VALUES ('654', 'Maitre Pandasiman');
INSERT INTO `npc_name` VALUES ('705', 'Maître Pandore');
INSERT INTO `npc_name` VALUES ('1222', 'Maître Pifo');
INSERT INTO `npc_name` VALUES ('128', 'Maître Roublard');
INSERT INTO `npc_name` VALUES ('219', 'Majono Takubin');
INSERT INTO `npc_name` VALUES ('443', 'Makdo Peule');
INSERT INTO `npc_name` VALUES ('242', 'Mak Gahan');
INSERT INTO `npc_name` VALUES ('326', 'Malicia Misère');
INSERT INTO `npc_name` VALUES ('923', 'Mali Key');
INSERT INTO `npc_name` VALUES ('389', 'Mama Ayuto');
INSERT INTO `npc_name` VALUES ('391', 'Mam Hikofre');
INSERT INTO `npc_name` VALUES ('706', 'Mamowa');
INSERT INTO `npc_name` VALUES ('610', 'Manganeze Pyrite');
INSERT INTO `npc_name` VALUES ('768', 'Marcelle Rouste');
INSERT INTO `npc_name` VALUES ('637', 'Marchande Petite Etoile');
INSERT INTO `npc_name` VALUES ('241', 'Marge Gondersun');
INSERT INTO `npc_name` VALUES ('822', 'Marie Zoto');
INSERT INTO `npc_name` VALUES ('394', 'Marine Lond');
INSERT INTO `npc_name` VALUES ('437', 'Marlonebrando Peule');
INSERT INTO `npc_name` VALUES ('453', 'Marp');
INSERT INTO `npc_name` VALUES ('983', 'Marquis');
INSERT INTO `npc_name` VALUES ('229', 'Marsel Leax');
INSERT INTO `npc_name` VALUES ('887', 'Marylork');
INSERT INTO `npc_name` VALUES ('688', 'Marzwel le Gobelin');
INSERT INTO `npc_name` VALUES ('752', 'Mashino');
INSERT INTO `npc_name` VALUES ('807', 'Maskara');
INSERT INTO `npc_name` VALUES ('886', 'Ma\'ster Donge');
INSERT INTO `npc_name` VALUES ('885', 'Matu Vuh');
INSERT INTO `npc_name` VALUES ('205', 'Maude Ere');
INSERT INTO `npc_name` VALUES ('780', 'Mawy Ingalsse');
INSERT INTO `npc_name` VALUES ('120', 'Max');
INSERT INTO `npc_name` VALUES ('397', 'Maxims');
INSERT INTO `npc_name` VALUES ('696', 'Maximus');
INSERT INTO `npc_name` VALUES ('366', 'Meneur Rocopal');
INSERT INTO `npc_name` VALUES ('468', 'Menge Paca');
INSERT INTO `npc_name` VALUES ('372', 'Mente Heur ');
INSERT INTO `npc_name` VALUES ('495', 'Meow Moew');
INSERT INTO `npc_name` VALUES ('356', 'Mèr');
INSERT INTO `npc_name` VALUES ('603', 'Mercenaire d\'Astrub');
INSERT INTO `npc_name` VALUES ('525', 'Mercenaire d\'Astrub');
INSERT INTO `npc_name` VALUES ('526', 'Mercenaire d\'Astrub');
INSERT INTO `npc_name` VALUES ('527', 'Mercenaire d\'Astrub');
INSERT INTO `npc_name` VALUES ('604', 'Mercenaire d\'Astrub');
INSERT INTO `npc_name` VALUES ('528', 'Mercenaire d\'Astrub');
INSERT INTO `npc_name` VALUES ('1010', 'Merlan l\'Enchaîneur');
INSERT INTO `npc_name` VALUES ('811', 'Metag Robill');
INSERT INTO `npc_name` VALUES ('442', 'Micado Peule');
INSERT INTO `npc_name` VALUES ('723', 'Milice de Brâkmar');
INSERT INTO `npc_name` VALUES ('339', 'Milicien');
INSERT INTO `npc_name` VALUES ('974', 'Milicien équipé');
INSERT INTO `npc_name` VALUES ('862', 'Milicien Kerubim');
INSERT INTO `npc_name` VALUES ('873', 'Milicien Kerubim');
INSERT INTO `npc_name` VALUES ('860', 'Milicien Kerubim');
INSERT INTO `npc_name` VALUES ('861', 'Milicien Kerubim');
INSERT INTO `npc_name` VALUES ('735', 'Milicienne de Bonta');
INSERT INTO `npc_name` VALUES ('734', 'Milicienne de Brâkmar');
INSERT INTO `npc_name` VALUES ('224', 'Milie Reilloc');
INSERT INTO `npc_name` VALUES ('277', 'Milone Corichel');
INSERT INTO `npc_name` VALUES ('268', 'Mimi Fista');
INSERT INTO `npc_name` VALUES ('404', 'Miss Reeze Teurf');
INSERT INTO `npc_name` VALUES ('742', 'Monabella');
INSERT INTO `npc_name` VALUES ('474', 'Mon\'Hawt\'Wit\'');
INSERT INTO `npc_name` VALUES ('819', 'Monsieur El');
INSERT INTO `npc_name` VALUES ('473', 'Montrakwartz');
INSERT INTO `npc_name` VALUES ('160', 'Moon');
INSERT INTO `npc_name` VALUES ('90', 'Mori Arty');
INSERT INTO `npc_name` VALUES ('1041', 'Morrie Gane');
INSERT INTO `npc_name` VALUES ('221', 'Moub Reicifitra');
INSERT INTO `npc_name` VALUES ('829', 'Moumoule essai');
INSERT INTO `npc_name` VALUES ('826', 'Mouss Bouff');
INSERT INTO `npc_name` VALUES ('943', 'Mulèze');
INSERT INTO `npc_name` VALUES ('365', 'Mulic Bere');
INSERT INTO `npc_name` VALUES ('841', 'Mulou Grankrok');
INSERT INTO `npc_name` VALUES ('239', 'Musa ');
INSERT INTO `npc_name` VALUES ('687', 'Musha l\'Oni');
INSERT INTO `npc_name` VALUES ('730', 'Nacf Virgil, vendeur de Parchemins');
INSERT INTO `npc_name` VALUES ('651', 'Nakunne');
INSERT INTO `npc_name` VALUES ('1096', 'Nana moche qui rit');
INSERT INTO `npc_name` VALUES ('208', 'Nani Tago');
INSERT INTO `npc_name` VALUES ('972', 'Nara');
INSERT INTO `npc_name` VALUES ('622', 'Narber Dapiwa le Marchand');
INSERT INTO `npc_name` VALUES ('704', 'Narber Rihen Levihawa');
INSERT INTO `npc_name` VALUES ('231', 'Ned Etsith');
INSERT INTO `npc_name` VALUES ('1117', 'Néforun');
INSERT INTO `npc_name` VALUES ('210', 'Neige');
INSERT INTO `npc_name` VALUES ('1105', 'Nek\'Ro Nomikon');
INSERT INTO `npc_name` VALUES ('479', 'Nepra Lido');
INSERT INTO `npc_name` VALUES ('659', 'Nergal');
INSERT INTO `npc_name` VALUES ('514', 'Nervous Brakdoun');
INSERT INTO `npc_name` VALUES ('109', 'Ness Laye');
INSERT INTO `npc_name` VALUES ('186', 'Niamuh Boulkier');
INSERT INTO `npc_name` VALUES ('486', 'Nibé Lulle');
INSERT INTO `npc_name` VALUES ('1128', 'Nibor Dépitré');
INSERT INTO `npc_name` VALUES ('770', 'Nikos Monote');
INSERT INTO `npc_name` VALUES ('286', 'Nim Nei');
INSERT INTO `npc_name` VALUES ('441', 'Ninetainedo Peule');
INSERT INTO `npc_name` VALUES ('298', 'Nissacram');
INSERT INTO `npc_name` VALUES ('732', 'Nistracolamus');
INSERT INTO `npc_name` VALUES ('902', 'Noble de la cour');
INSERT INTO `npc_name` VALUES ('794', 'Nopa Abra');
INSERT INTO `npc_name` VALUES ('792', 'Nopa Bouftou');
INSERT INTO `npc_name` VALUES ('793', 'Nopa Bworker');
INSERT INTO `npc_name` VALUES ('791', 'Nopa Prespic');
INSERT INTO `npc_name` VALUES ('1217', 'Norach');
INSERT INTO `npc_name` VALUES ('971', 'Norb');
INSERT INTO `npc_name` VALUES ('405', 'Notend Less');
INSERT INTO `npc_name` VALUES ('809', 'Nounou Veauté');
INSERT INTO `npc_name` VALUES ('417', 'Nours Eulbu');
INSERT INTO `npc_name` VALUES ('725', 'Nowa');
INSERT INTO `npc_name` VALUES ('796', 'Obad');
INSERT INTO `npc_name` VALUES ('510', 'Ogivol Scalarcin');
INSERT INTO `npc_name` VALUES ('475', 'Ogivol Scalarcin');
INSERT INTO `npc_name` VALUES ('276', 'Oket');
INSERT INTO `npc_name` VALUES ('484', 'Oli Venders');
INSERT INTO `npc_name` VALUES ('216', 'Onnel Passepat');
INSERT INTO `npc_name` VALUES ('434', 'Orlando Peule');
INSERT INTO `npc_name` VALUES ('162', 'Ortimus');
INSERT INTO `npc_name` VALUES ('756', 'Oshar Marif');
INSERT INTO `npc_name` VALUES ('753', 'Oshima');
INSERT INTO `npc_name` VALUES ('297', 'Oshimo');
INSERT INTO `npc_name` VALUES ('111', 'Otho Laringo');
INSERT INTO `npc_name` VALUES ('914', 'Otomaï');
INSERT INTO `npc_name` VALUES ('183', 'Oto Mustam');
INSERT INTO `npc_name` VALUES ('738', 'Oyster');
INSERT INTO `npc_name` VALUES ('452', 'Oz Dralett');
INSERT INTO `npc_name` VALUES ('123', 'Ozen Le sage');
INSERT INTO `npc_name` VALUES ('511', 'Padgref Demoël');
INSERT INTO `npc_name` VALUES ('821', 'Paindep');
INSERT INTO `npc_name` VALUES ('1458', 'Pancarte usée');
INSERT INTO `npc_name` VALUES ('1226', 'Pandale Douce');
INSERT INTO `npc_name` VALUES ('1090', 'Pandalida');
INSERT INTO `npc_name` VALUES ('644', 'Pandiwan Kenobi');
INSERT INTO `npc_name` VALUES ('619', 'Papy nowal');
INSERT INTO `npc_name` VALUES ('315', 'Paro Cabanne');
INSERT INTO `npc_name` VALUES ('814', 'Pat Akess');
INSERT INTO `npc_name` VALUES ('407', 'Pat Pott');
INSERT INTO `npc_name` VALUES ('931', 'Paulette Pain-bèche');
INSERT INTO `npc_name` VALUES ('960', 'Pauquet [WIP]');
INSERT INTO `npc_name` VALUES ('1162', 'Pavu Papry');
INSERT INTO `npc_name` VALUES ('863', 'Paysan d\'Incarnam');
INSERT INTO `npc_name` VALUES ('883', 'Pêcheur d\'Incarnam');
INSERT INTO `npc_name` VALUES ('940', 'Peggy la Porkass');
INSERT INTO `npc_name` VALUES ('710', 'Peki Peki');
INSERT INTO `npc_name` VALUES ('697', 'Penih Tencier');
INSERT INTO `npc_name` VALUES ('1', 'Percepteur');
INSERT INTO `npc_name` VALUES ('195', 'Père Furax');
INSERT INTO `npc_name` VALUES ('1227', 'Phil Arthur');
INSERT INTO `npc_name` VALUES ('470', 'Phite Pouque');
INSERT INTO `npc_name` VALUES ('806', 'Piélant');
INSERT INTO `npc_name` VALUES ('805', 'Piétinor le bourrin');
INSERT INTO `npc_name` VALUES ('839', 'Pinta Gone');
INSERT INTO `npc_name` VALUES ('869', 'Piou');
INSERT INTO `npc_name` VALUES ('858', 'Pipelette Nhin');
INSERT INTO `npc_name` VALUES ('662', 'Pladawa');
INSERT INTO `npc_name` VALUES ('837', 'Plastik Gobelait');
INSERT INTO `npc_name` VALUES ('451', 'Pleur Nycheuz');
INSERT INTO `npc_name` VALUES ('635', 'Plumawa la Marchande');
INSERT INTO `npc_name` VALUES ('825', 'Pol Bokuz');
INSERT INTO `npc_name` VALUES ('929', 'Polka Merer');
INSERT INTO `npc_name` VALUES ('648', 'Poochan');
INSERT INTO `npc_name` VALUES ('647', 'Poochan');
INSERT INTO `npc_name` VALUES ('850', 'Poss\'Ybel Nhin');
INSERT INTO `npc_name` VALUES ('857', 'Posteur Nhin ');
INSERT INTO `npc_name` VALUES ('848', 'Potan Nhin');
INSERT INTO `npc_name` VALUES ('1123', 'Poursuivant brâkmarien');
INSERT INTO `npc_name` VALUES ('386', 'Pousse-pousse');
INSERT INTO `npc_name` VALUES ('163', 'Prêtre');
INSERT INTO `npc_name` VALUES ('904', 'Prince d\'Wa');
INSERT INTO `npc_name` VALUES ('926', 'Professeur Fournesol');
INSERT INTO `npc_name` VALUES ('153', 'Promoteur de l\'agence Touriste');
INSERT INTO `npc_name` VALUES ('970', 'Puissant milicien bontarien');
INSERT INTO `npc_name` VALUES ('357', 'Puja Mustam');
INSERT INTO `npc_name` VALUES ('624', 'Pyrite');
INSERT INTO `npc_name` VALUES ('516', 'Qil Bil');
INSERT INTO `npc_name` VALUES ('110', 'Quincy Praïze');
INSERT INTO `npc_name` VALUES ('342', 'Raaga');
INSERT INTO `npc_name` VALUES ('341', 'Raaga');
INSERT INTO `npc_name` VALUES ('544', 'Radlu Minite le Mineur Sombre');
INSERT INTO `npc_name` VALUES ('264', 'Rafaj');
INSERT INTO `npc_name` VALUES ('66', 'Ralgout');
INSERT INTO `npc_name` VALUES ('329', 'Ranj Thé');
INSERT INTO `npc_name` VALUES ('835', 'Raxitik');
INSERT INTO `npc_name` VALUES ('1042', 'Raymond Santho');
INSERT INTO `npc_name` VALUES ('945', 'Razbitume');
INSERT INTO `npc_name` VALUES ('319', 'Rei Nisuc');
INSERT INTO `npc_name` VALUES ('190', 'Rei Rosert');
INSERT INTO `npc_name` VALUES ('259', 'Rekojel');
INSERT INTO `npc_name` VALUES ('1050', 'Renégat bontarien');
INSERT INTO `npc_name` VALUES ('371', 'Reuth Rezed');
INSERT INTO `npc_name` VALUES ('327', 'Reve Nocturne');
INSERT INTO `npc_name` VALUES ('438', 'Ricardo Peule');
INSERT INTO `npc_name` VALUES ('45', 'Rigal Main Crochue');
INSERT INTO `npc_name` VALUES ('427', 'Rihine Pléhouverte');
INSERT INTO `npc_name` VALUES ('313', 'Rika Charmé');
INSERT INTO `npc_name` VALUES ('355', 'Rimaraf');
INSERT INTO `npc_name` VALUES ('38', 'Rish Claymore');
INSERT INTO `npc_name` VALUES ('1100', 'Riyou Tchevlakouk');
INSERT INTO `npc_name` VALUES ('237', 'Roca Charmé');
INSERT INTO `npc_name` VALUES ('741', 'Rocco Fidelio');
INSERT INTO `npc_name` VALUES ('494', 'Rok Elreuss');
INSERT INTO `npc_name` VALUES ('685', 'Rok Gnorok');
INSERT INTO `npc_name` VALUES ('633', 'Ronald le Sage Lenald');
INSERT INTO `npc_name` VALUES ('1035', 'Ronan le Blagueur');
INSERT INTO `npc_name` VALUES ('108', 'Ronsha');
INSERT INTO `npc_name` VALUES ('598', 'Rose Artempeth');
INSERT INTO `npc_name` VALUES ('173', 'Rotabla le berger triste');
INSERT INTO `npc_name` VALUES ('1454', 'Rouge Blard');
INSERT INTO `npc_name` VALUES ('272', 'Roupi Chipon ');
INSERT INTO `npc_name` VALUES ('761', 'Rubise');
INSERT INTO `npc_name` VALUES ('274', 'Rucar');
INSERT INTO `npc_name` VALUES ('408', 'Rudla Faurtune');
INSERT INTO `npc_name` VALUES ('1435', 'Rudy Stribu');
INSERT INTO `npc_name` VALUES ('694', 'Runago Gho');
INSERT INTO `npc_name` VALUES ('695', 'Runoga Gha');
INSERT INTO `npc_name` VALUES ('275', 'Runyac');
INSERT INTO `npc_name` VALUES ('218', 'Ruth Banke');
INSERT INTO `npc_name` VALUES ('1092', 'Sabine');
INSERT INTO `npc_name` VALUES ('496', 'Sadadi Sama');
INSERT INTO `npc_name` VALUES ('984', 'Sadida en cape bontarienne');
INSERT INTO `npc_name` VALUES ('472', 'Saketsu');
INSERT INTO `npc_name` VALUES ('102', 'Salamon Rudy');
INSERT INTO `npc_name` VALUES ('463', 'Sam Croa');
INSERT INTO `npc_name` VALUES ('228', 'Sanagouk');
INSERT INTO `npc_name` VALUES ('291', 'Sanglier des plaines');
INSERT INTO `npc_name` VALUES ('764', 'Saphira');
INSERT INTO `npc_name` VALUES ('351', 'Satirev Refibrom ');
INSERT INTO `npc_name` VALUES ('335', 'Sbab ');
INSERT INTO `npc_name` VALUES ('245', 'Seci Ves');
INSERT INTO `npc_name` VALUES ('1225', 'Sel Dawa');
INSERT INTO `npc_name` VALUES ('26', 'Séline');
INSERT INTO `npc_name` VALUES ('866', 'Semper Idefix');
INSERT INTO `npc_name` VALUES ('212', 'Sen Eiser');
INSERT INTO `npc_name` VALUES ('344', 'Sentinelle Chô Peleux');
INSERT INTO `npc_name` VALUES ('346', 'Sentinelle Eche Pediot');
INSERT INTO `npc_name` VALUES ('347', 'Sentinelle Emide Routte');
INSERT INTO `npc_name` VALUES ('343', 'Sentinelle Tevi Lup');
INSERT INTO `npc_name` VALUES ('345', 'Sentinelle Yourig Ella');
INSERT INTO `npc_name` VALUES ('455', 'Seria');
INSERT INTO `npc_name` VALUES ('165', 'Servante');
INSERT INTO `npc_name` VALUES ('270', 'Servante démoniaque');
INSERT INTO `npc_name` VALUES ('889', 'Serveuse de Grobid');
INSERT INTO `npc_name` VALUES ('41', 'Setag');
INSERT INTO `npc_name` VALUES ('502', 'Seth Sourcet');
INSERT INTO `npc_name` VALUES ('894', 'Seth Zérauséro');
INSERT INTO `npc_name` VALUES ('480', 'Setsinbol');
INSERT INTO `npc_name` VALUES ('232', 'Sey jissey');
INSERT INTO `npc_name` VALUES ('462', 'Shani Sings');
INSERT INTO `npc_name` VALUES ('187', 'Shere Hacanon');
INSERT INTO `npc_name` VALUES ('54', 'Shika Ingalsse');
INSERT INTO `npc_name` VALUES ('423', 'Silimote Fougaris');
INSERT INTO `npc_name` VALUES ('91', 'Simgood le marin');
INSERT INTO `npc_name` VALUES ('1104', 'Sim le Soft');
INSERT INTO `npc_name` VALUES ('428', 'Sirmine Daguiero');
INSERT INTO `npc_name` VALUES ('787', 'Sister Halliwell');
INSERT INTO `npc_name` VALUES ('760', 'Skeunk');
INSERT INTO `npc_name` VALUES ('612', 'Sko Balt');
INSERT INTO `npc_name` VALUES ('650', 'Sli');
INSERT INTO `npc_name` VALUES ('801', 'Snobin Parchume');
INSERT INTO `npc_name` VALUES ('1088', 'Snori Nairb');
INSERT INTO `npc_name` VALUES ('457', 'Soki');
INSERT INTO `npc_name` VALUES ('133', 'Sosh');
INSERT INTO `npc_name` VALUES ('280', 'Sotsiah Peh');
INSERT INTO `npc_name` VALUES ('660', 'Soukawa le Marchand');
INSERT INTO `npc_name` VALUES ('491', 'Soun Rinos');
INSERT INTO `npc_name` VALUES ('289', 'Sperwel');
INSERT INTO `npc_name` VALUES ('935', 'Spitte Fayeur');
INSERT INTO `npc_name` VALUES ('745', 'Squale Lerouge');
INSERT INTO `npc_name` VALUES ('681', 'Stayfun Bonnawa');
INSERT INTO `npc_name` VALUES ('856', 'Str\'huit Nhin');
INSERT INTO `npc_name` VALUES ('843', 'Struk\'toer Nhin');
INSERT INTO `npc_name` VALUES ('402', 'Sû Benhir ');
INSERT INTO `npc_name` VALUES ('1038', 'Suebur Dirgah');
INSERT INTO `npc_name` VALUES ('623', 'Surivitna le Shaman');
INSERT INTO `npc_name` VALUES ('1234', 'Syn Jorge');
INSERT INTO `npc_name` VALUES ('307', 'Tabach le Greffier');
INSERT INTO `npc_name` VALUES ('198', 'Tabi de Grace Malcean');
INSERT INTO `npc_name` VALUES ('969', 'Tacticien de Bonta');
INSERT INTO `npc_name` VALUES ('273', 'Tadosse');
INSERT INTO `npc_name` VALUES ('424', 'Tajide Ragalde');
INSERT INTO `npc_name` VALUES ('788', 'Takeshi No Pain');
INSERT INTO `npc_name` VALUES ('287', 'Tamiat');
INSERT INTO `npc_name` VALUES ('708', 'Tanukouï San');
INSERT INTO `npc_name` VALUES ('181', 'Tarazed');
INSERT INTO `npc_name` VALUES ('392', 'Tarazed');
INSERT INTO `npc_name` VALUES ('184', 'Tarche');
INSERT INTO `npc_name` VALUES ('293', 'Tavernier Alakarte');
INSERT INTO `npc_name` VALUES ('292', 'Tavernier Bagrutte');
INSERT INTO `npc_name` VALUES ('294', 'Tavernier Chopenbois');
INSERT INTO `npc_name` VALUES ('711', 'Tavernier du Ripate');
INSERT INTO `npc_name` VALUES ('296', 'Tavernier Ferayeur');
INSERT INTO `npc_name` VALUES ('240', 'Tavernier Feubuk');
INSERT INTO `npc_name` VALUES ('295', 'Tavernier Pinchaut');
INSERT INTO `npc_name` VALUES ('244', 'Tavernier Tabasse');
INSERT INTO `npc_name` VALUES ('113', 'Téha Chicks');
INSERT INTO `npc_name` VALUES ('464', 'Tek Abir');
INSERT INTO `npc_name` VALUES ('260', 'Tek Apout');
INSERT INTO `npc_name` VALUES ('466', 'Tekat Bra');
INSERT INTO `npc_name` VALUES ('870', 'Tenva Lakruche');
INSERT INTO `npc_name` VALUES ('83', 'Teransse Houlle');
INSERT INTO `npc_name` VALUES ('1049', 'Terra Cogita');
INSERT INTO `npc_name` VALUES ('1046', 'Terra Tibya');
INSERT INTO `npc_name` VALUES ('964', 'Tertofi Ablaru');
INSERT INTO `npc_name` VALUES ('912', 'Test');
INSERT INTO `npc_name` VALUES ('731', 'Test');
INSERT INTO `npc_name` VALUES ('944', 'Test Nyx [WIP]');
INSERT INTO `npc_name` VALUES ('978', 'Thanos');
INSERT INTO `npc_name` VALUES ('1121', 'Thomas Sacre');
INSERT INTO `npc_name` VALUES ('483', 'Ticra');
INSERT INTO `npc_name` VALUES ('1455', 'Timmy Leuphann');
INSERT INTO `npc_name` VALUES ('674', 'Timouss');
INSERT INTO `npc_name` VALUES ('941', 'Tina Montini');
INSERT INTO `npc_name` VALUES ('773', 'Tishima');
INSERT INTO `npc_name` VALUES ('838', 'Titi Gobelait');
INSERT INTO `npc_name` VALUES ('867', 'Tom Legeux');
INSERT INTO `npc_name` VALUES ('611', 'Tong Sten');
INSERT INTO `npc_name` VALUES ('194', 'Torche');
INSERT INTO `npc_name` VALUES ('492', 'Touh Flowa');
INSERT INTO `npc_name` VALUES ('693', 'Tourist');
INSERT INTO `npc_name` VALUES ('702', 'Tourista');
INSERT INTO `npc_name` VALUES ('613', 'Toyo Dzink');
INSERT INTO `npc_name` VALUES ('1115', 'Trape');
INSERT INTO `npc_name` VALUES ('1275', 'Tréfan Caza');
INSERT INTO `npc_name` VALUES ('1276', 'Tréfan Caza');
INSERT INTO `npc_name` VALUES ('189', 'Trev Pelsantery');
INSERT INTO `npc_name` VALUES ('320', 'Trof Hapyus');
INSERT INTO `npc_name` VALUES ('488', 'Trois-Fleurs');
INSERT INTO `npc_name` VALUES ('364', 'Trojen Tihpor');
INSERT INTO `npc_name` VALUES ('1080', 'Trok');
INSERT INTO `npc_name` VALUES ('916', 'Trône d\'Allister');
INSERT INTO `npc_name` VALUES ('421', 'Trool Blagueur');
INSERT INTO `npc_name` VALUES ('419', 'Trool Farceur');
INSERT INTO `npc_name` VALUES ('420', 'Trool Rieur');
INSERT INTO `npc_name` VALUES ('283', 'Trysy');
INSERT INTO `npc_name` VALUES ('238', 'Tsog');
INSERT INTO `npc_name` VALUES ('233', 'Ture Inge');
INSERT INTO `npc_name` VALUES ('977', 'Turorte');
INSERT INTO `npc_name` VALUES ('166', 'Uba Tessé');
INSERT INTO `npc_name` VALUES ('534', 'Uneul Nak');
INSERT INTO `npc_name` VALUES ('536', 'Unhorel Nak');
INSERT INTO `npc_name` VALUES ('537', 'Unkouy Nak');
INSERT INTO `npc_name` VALUES ('535', 'Unortel Nak');
INSERT INTO `npc_name` VALUES ('564', 'Unterix Unter');
INSERT INTO `npc_name` VALUES ('924', 'Ursula en Tresses');
INSERT INTO `npc_name` VALUES ('269', 'Vagabond');
INSERT INTO `npc_name` VALUES ('803', 'Valcor');
INSERT INTO `npc_name` VALUES ('907', 'Valet Deauj');
INSERT INTO `npc_name` VALUES ('908', 'Valet Deauj');
INSERT INTO `npc_name` VALUES ('911', 'Valet Lelisdanla');
INSERT INTO `npc_name` VALUES ('737', 'Vark Agram');
INSERT INTO `npc_name` VALUES ('557', 'Vendeur Alchimiste d\'Astrub');
INSERT INTO `npc_name` VALUES ('570', 'Vendeur Alchimiste de Bonta');
INSERT INTO `npc_name` VALUES ('584', 'Vendeur Alchimiste de Brâkmar');
INSERT INTO `npc_name` VALUES ('714', 'Vendeur Animaux de Bonta');
INSERT INTO `npc_name` VALUES ('715', 'Vendeur Animaux de Brâkmar');
INSERT INTO `npc_name` VALUES ('555', 'Vendeur Bijoutier d\'Astrub');
INSERT INTO `npc_name` VALUES ('572', 'Vendeur Bijoutier de Bonta');
INSERT INTO `npc_name` VALUES ('586', 'Vendeur Bijoutier de Brâkmar');
INSERT INTO `npc_name` VALUES ('553', 'Vendeur Boucher d\'Astrub');
INSERT INTO `npc_name` VALUES ('678', 'Vendeur Bouclier de Pandala');
INSERT INTO `npc_name` VALUES ('561', 'Vendeur Boulanger d\'Astrub');
INSERT INTO `npc_name` VALUES ('575', 'Vendeur Boulanger de Bonta');
INSERT INTO `npc_name` VALUES ('589', 'Vendeur Boulanger de Brâkmar');
INSERT INTO `npc_name` VALUES ('1220', 'Vendeur Bricoleur d\'Astrub');
INSERT INTO `npc_name` VALUES ('720', 'Vendeur Bricoleur de Bonta');
INSERT INTO `npc_name` VALUES ('721', 'Vendeur Bricoleur de Brâkmar');
INSERT INTO `npc_name` VALUES ('554', 'Vendeur Bûcheron d\'Astrub');
INSERT INTO `npc_name` VALUES ('578', 'Vendeur Bûcheron de Bonta');
INSERT INTO `npc_name` VALUES ('591', 'Vendeur Bûcheron de Brâkmar');
INSERT INTO `npc_name` VALUES ('563', 'Vendeur Chasseur d\'Astrub');
INSERT INTO `npc_name` VALUES ('552', 'Vendeur Cordonnier d\'Astrub');
INSERT INTO `npc_name` VALUES ('573', 'Vendeur Cordonnier de Bonta');
INSERT INTO `npc_name` VALUES ('587', 'Vendeur Cordonnier de Brâkmar');
INSERT INTO `npc_name` VALUES ('698', 'Vendeur d\'âmes de Bonta');
INSERT INTO `npc_name` VALUES ('699', 'Vendeur d\'âmes de Brâkmar');
INSERT INTO `npc_name` VALUES ('1270', 'Vendeur d\'Amulettes');
INSERT INTO `npc_name` VALUES ('1271', 'Vendeur d\'Anneaux');
INSERT INTO `npc_name` VALUES ('1274', 'Vendeur d\'Armes');
INSERT INTO `npc_name` VALUES ('1272', 'Vendeur de Bottes');
INSERT INTO `npc_name` VALUES ('1286', 'Vendeur de Boucliers');
INSERT INTO `npc_name` VALUES ('1158', 'Vendeur de capes');
INSERT INTO `npc_name` VALUES ('1273', 'Vendeur de Ceintures');
INSERT INTO `npc_name` VALUES ('812', 'Vendeur de chapeaux');
INSERT INTO `npc_name` VALUES ('716', 'Vendeur de Documents de Bonta');
INSERT INTO `npc_name` VALUES ('1053', 'Vendeur de Dofus');
INSERT INTO `npc_name` VALUES ('952', 'Vendeur de parchemins');
INSERT INTO `npc_name` VALUES ('579', 'Vendeur de Poisson de Bonta');
INSERT INTO `npc_name` VALUES ('593', 'Vendeur de Poisson de Brâkmar');
INSERT INTO `npc_name` VALUES ('546', 'Vendeur de Ressources d\'Astrub');
INSERT INTO `npc_name` VALUES ('574', 'Vendeur de Ressources de Bonta');
INSERT INTO `npc_name` VALUES ('588', 'Vendeur de Ressources de Brâkmar');
INSERT INTO `npc_name` VALUES ('790', 'Vendeur de runes');
INSERT INTO `npc_name` VALUES ('580', 'Vendeur de Viande de Bonta');
INSERT INTO `npc_name` VALUES ('592', 'Vendeur de Viande de Brâkmar');
INSERT INTO `npc_name` VALUES ('717', 'Vendeur Documents de Brâkmar');
INSERT INTO `npc_name` VALUES ('1221', 'Vendeur Fées d\'artifice');
INSERT INTO `npc_name` VALUES ('547', 'Vendeur Forgeron d\'Astrub');
INSERT INTO `npc_name` VALUES ('567', 'Vendeur Forgeron de Bonta');
INSERT INTO `npc_name` VALUES ('581', 'Vendeur Forgeron de Brâkmar');
INSERT INTO `npc_name` VALUES ('722', 'Vendeur Milice de Bonta');
INSERT INTO `npc_name` VALUES ('550', 'Vendeur Mineur d\'Astrub');
INSERT INTO `npc_name` VALUES ('568', 'Vendeur Mineur de Bonta');
INSERT INTO `npc_name` VALUES ('582', 'Vendeur Mineur de Brâkmar');
INSERT INTO `npc_name` VALUES ('551', 'Vendeur Paysan d\'Astrub');
INSERT INTO `npc_name` VALUES ('576', 'Vendeur Paysan de Bonta');
INSERT INTO `npc_name` VALUES ('590', 'Vendeur Paysan de Brâkmar');
INSERT INTO `npc_name` VALUES ('562', 'Vendeur Pêcheur d\'Astrub');
INSERT INTO `npc_name` VALUES ('559', 'Vendeur Poissonnier d\'Astrub');
INSERT INTO `npc_name` VALUES ('718', 'Vendeur Runes de Bonta');
INSERT INTO `npc_name` VALUES ('719', 'Vendeur Runes de Brâkmar');
INSERT INTO `npc_name` VALUES ('548', 'Vendeur Sculpteur d\'Astrub');
INSERT INTO `npc_name` VALUES ('569', 'Vendeur Sculpteur de Bonta');
INSERT INTO `npc_name` VALUES ('583', 'Vendeur Sculpteur de Brâkmar');
INSERT INTO `npc_name` VALUES ('560', 'Vendeur Tailleur d\'Astrub');
INSERT INTO `npc_name` VALUES ('571', 'Vendeur Tailleur de Bonta');
INSERT INTO `npc_name` VALUES ('585', 'Vendeur Tailleur de Brâkmar');
INSERT INTO `npc_name` VALUES ('743', 'Verumacha');
INSERT INTO `npc_name` VALUES ('204', 'Vicky Facheyon');
INSERT INTO `npc_name` VALUES ('169', 'Vid Cheber');
INSERT INTO `npc_name` VALUES ('84', 'Vil Smisse');
INSERT INTO `npc_name` VALUES ('774', 'Virgil');
INSERT INTO `npc_name` VALUES ('1095', 'Voleur de Brâkmar');
INSERT INTO `npc_name` VALUES ('1131', 'Voleur de Brâkmar');
INSERT INTO `npc_name` VALUES ('1134', 'Voleur de Brâkmar');
INSERT INTO `npc_name` VALUES ('1133', 'Voleur de Brâkmar');
INSERT INTO `npc_name` VALUES ('418', 'Vylag Hoise');
INSERT INTO `npc_name` VALUES ('141', 'Wabbit du Matin Pewlant');
INSERT INTO `npc_name` VALUES ('143', 'Wabbit du Midi Wayonnant');
INSERT INTO `npc_name` VALUES ('144', 'Wabbit du Soiw Woulant');
INSERT INTO `npc_name` VALUES ('748', 'Walak');
INSERT INTO `npc_name` VALUES ('565', 'Waldo Pyrite');
INSERT INTO `npc_name` VALUES ('447', 'Wally Elconom');
INSERT INTO `npc_name` VALUES ('566', 'Walter Pyrite');
INSERT INTO `npc_name` VALUES ('640', 'Wanald le Sage Lenald');
INSERT INTO `npc_name` VALUES ('137', 'Wa Wabbit');
INSERT INTO `npc_name` VALUES ('506', 'Wilde Pyrite');
INSERT INTO `npc_name` VALUES ('203', 'William Lenglad');
INSERT INTO `npc_name` VALUES ('146', 'Wob');
INSERT INTO `npc_name` VALUES ('196', 'Wogew l\'hewmite');
INSERT INTO `npc_name` VALUES ('966', 'Xarthan');
INSERT INTO `npc_name` VALUES ('1091', 'Xélora Busai');
INSERT INTO `npc_name` VALUES ('859', 'Xelorat Masket');
INSERT INTO `npc_name` VALUES ('963', 'Xephirès');
INSERT INTO `npc_name` VALUES ('387', 'Yan Chenap');
INSERT INTO `npc_name` VALUES ('309', 'Ybaul, Greffière');
INSERT INTO `npc_name` VALUES ('1098', 'Ybur Effel');
INSERT INTO `npc_name` VALUES ('692', 'Yenawa le Banquier');
INSERT INTO `npc_name` VALUES ('597', 'Ygat Chouse');
INSERT INTO `npc_name` VALUES ('450', 'Yke Harou');
INSERT INTO `npc_name` VALUES ('459', 'Yol Grivind');
INSERT INTO `npc_name` VALUES ('393', 'Yova Etna');
INSERT INTO `npc_name` VALUES ('595', 'Yul Brinner');
INSERT INTO `npc_name` VALUES ('211', 'Yvan Amarh');
INSERT INTO `npc_name` VALUES ('465', 'Yve Konpetmin');
INSERT INTO `npc_name` VALUES ('707', 'Zamawa');
INSERT INTO `npc_name` VALUES ('689', 'Zatoïshwan');
INSERT INTO `npc_name` VALUES ('884', 'Zaulie Portklais');
INSERT INTO `npc_name` VALUES ('409', 'Ze Krow');
INSERT INTO `npc_name` VALUES ('42', 'Zeurg');
INSERT INTO `npc_name` VALUES ('1233', 'Zezette Nowel');
INSERT INTO `npc_name` VALUES ('789', 'Ziho');
INSERT INTO `npc_name` VALUES ('282', 'ZolTAN');
INSERT INTO `npc_name` VALUES ('478', 'Ztiv Oztin');