INSERT INTO `quest_name` VALUES ('3', 'La discorde végétale');
INSERT INTO `quest_name` VALUES ('4', 'La complainte du chacha');
INSERT INTO `quest_name` VALUES ('5', 'De la difficulté à être Bijoutier');
INSERT INTO `quest_name` VALUES ('6', '(next) A la recherche du Coup-devin');
INSERT INTO `quest_name` VALUES ('7', 'Le dur labeur de Sram');
INSERT INTO `quest_name` VALUES ('8', 'Du sang froid !');
INSERT INTO `quest_name` VALUES ('9', 'Grain de folie à Astrub');
INSERT INTO `quest_name` VALUES ('10', 'Problème de livraison');
INSERT INTO `quest_name` VALUES ('11', 'Pleur Nycheuz');
INSERT INTO `quest_name` VALUES ('12', '(next) Livraison de Pizaille');
INSERT INTO `quest_name` VALUES ('13', 'Un ours dans la bouftonerie');
INSERT INTO `quest_name` VALUES ('14', 'La dernière mode');
INSERT INTO `quest_name` VALUES ('15', 'Une taupe de trop dans mon Astrub');
INSERT INTO `quest_name` VALUES ('16', 'Et une baguette de Dzibi, une !');
INSERT INTO `quest_name` VALUES ('18', 'Wogew l\'hewmite');
INSERT INTO `quest_name` VALUES ('19', '(next) La Maison Fantome');
INSERT INTO `quest_name` VALUES ('20', 'Epée : mode d\'emploi');
INSERT INTO `quest_name` VALUES ('21', 'Forgée sur un pari. A l\'Ecaflip simplement');
INSERT INTO `quest_name` VALUES ('22', 'La Quête Du Pabo');
INSERT INTO `quest_name` VALUES ('24', 'Vol...Age ?');
INSERT INTO `quest_name` VALUES ('25', 'Savoir de Crâ');
INSERT INTO `quest_name` VALUES ('26', 'Manuscrit de Terra Cogita');
INSERT INTO `quest_name` VALUES ('27', '(next)Maladie chronique');
INSERT INTO `quest_name` VALUES ('28', 'Le monocle de Wally');
INSERT INTO `quest_name` VALUES ('29', 'Retrouver Padgref Demoël');
INSERT INTO `quest_name` VALUES ('30', 'Retrouver Frakacia Leukocytine');
INSERT INTO `quest_name` VALUES ('31', 'Retrouver Nervoes Brakdoun');
INSERT INTO `quest_name` VALUES ('32', 'Retrouver Qil Bil');
INSERT INTO `quest_name` VALUES ('33', 'Retrouver Brumen Tinctorias');
INSERT INTO `quest_name` VALUES ('34', 'Retrouver Fouduglen L\'écureuil');
INSERT INTO `quest_name` VALUES ('35', 'Retrouver Ogivol Scalarcin');
INSERT INTO `quest_name` VALUES ('36', 'Bière en danger');
INSERT INTO `quest_name` VALUES ('37', 'Futuramakna');
INSERT INTO `quest_name` VALUES ('38', 'Les Enutrofs sont nos amis, il faut...');
INSERT INTO `quest_name` VALUES ('39', 'Initiation à la nature... des Sadidas.');
INSERT INTO `quest_name` VALUES ('40', 'Le Donjon de la reflexion');
INSERT INTO `quest_name` VALUES ('42', 'Fecaffe à mon troupeau');
INSERT INTO `quest_name` VALUES ('43', 'Chasse à l\'écureuil');
INSERT INTO `quest_name` VALUES ('44', 'Ne pas vendre la mèche avant de l\'avoir tuée');
INSERT INTO `quest_name` VALUES ('45', 'A la recherche des Enus disparus');
INSERT INTO `quest_name` VALUES ('47', 'Sandwich d\'Araknée');
INSERT INTO `quest_name` VALUES ('48', 'Tofu sous microscope');
INSERT INTO `quest_name` VALUES ('49', 'Plus de Nageant-infecte-cieux !');
INSERT INTO `quest_name` VALUES ('50', 'Flêches Cra-rakneene');
INSERT INTO `quest_name` VALUES ('53', 'Pauvre Kwikwi');
INSERT INTO `quest_name` VALUES ('52', 'Aiguilles de rats...');
INSERT INTO `quest_name` VALUES ('51', 'Dératisation !');
INSERT INTO `quest_name` VALUES ('55', 'Entraînement avec Tarche');
INSERT INTO `quest_name` VALUES ('59', 'Entraînement avec Torche');
INSERT INTO `quest_name` VALUES ('56', 'La tenancière Dame Cloude');
INSERT INTO `quest_name` VALUES ('57', 'Du pain pour les braves');
INSERT INTO `quest_name` VALUES ('58', 'Ned le dentiste');
INSERT INTO `quest_name` VALUES ('60', 'Cartes spéciales d\'Amayiro');
INSERT INTO `quest_name` VALUES ('61', 'On a volé le collier de la fille du maire');
INSERT INTO `quest_name` VALUES ('62', 'Pas de fainéants dans les rangs !');
INSERT INTO `quest_name` VALUES ('63', 'Première visite à Brâkmar');
INSERT INTO `quest_name` VALUES ('64', 'Un sanglier un peu trop agressif...');
INSERT INTO `quest_name` VALUES ('65', 'Du repos mais pas trop...');
INSERT INTO `quest_name` VALUES ('66', 'Recouvrement de dette à la Tabasse');
INSERT INTO `quest_name` VALUES ('67', 'Pot l\'agent double');
INSERT INTO `quest_name` VALUES ('68', 'De la poudre aux yeux de Brâkmar');
INSERT INTO `quest_name` VALUES ('69', 'Une brèche à Bonta');
INSERT INTO `quest_name` VALUES ('70', 'Quatre caisses à pied, ça use...');
INSERT INTO `quest_name` VALUES ('71', 'L\'élite squelettique');
INSERT INTO `quest_name` VALUES ('72', 'La foire du Trool suspectée');
INSERT INTO `quest_name` VALUES ('73', 'Le Tabi d\'Amayiro');
INSERT INTO `quest_name` VALUES ('74', 'Le fantôme de Tsog');
INSERT INTO `quest_name` VALUES ('75', 'Des anneaux sur le bout des doigts');
INSERT INTO `quest_name` VALUES ('76', 'La fureur du Holbaïd');
INSERT INTO `quest_name` VALUES ('77', 'Des capes Bontariennes');
INSERT INTO `quest_name` VALUES ('78', 'Corvée de patate');
INSERT INTO `quest_name` VALUES ('79', 'Lyeno, Abraknyde malgré lui');
INSERT INTO `quest_name` VALUES ('80', 'Au service de Danathor');
INSERT INTO `quest_name` VALUES ('81', 'Amayiro à l\'ombre du Champo');
INSERT INTO `quest_name` VALUES ('82', 'Le décès de Rimaraf');
INSERT INTO `quest_name` VALUES ('83', 'Poison de scorbute pour la prison');
INSERT INTO `quest_name` VALUES ('84', 'Dike Tarak, la menace');
INSERT INTO `quest_name` VALUES ('85', 'Des combats pas très légaux...');
INSERT INTO `quest_name` VALUES ('86', 'Mission de reconnaissance au cimetière');
INSERT INTO `quest_name` VALUES ('87', 'Extension du bâtiment de la milice');
INSERT INTO `quest_name` VALUES ('88', 'La lettre anonyme');
INSERT INTO `quest_name` VALUES ('89', 'Danathor a-t-il tort ?');
INSERT INTO `quest_name` VALUES ('90', 'Dix badges pour la bonne cause');
INSERT INTO `quest_name` VALUES ('91', 'Leçon de cuisine');
INSERT INTO `quest_name` VALUES ('92', 'Ras le bol de Lenglad');
INSERT INTO `quest_name` VALUES ('93', 'Dapyus n\'est pas doué');
INSERT INTO `quest_name` VALUES ('94', 'Les rats d\'Hyoactif');
INSERT INTO `quest_name` VALUES ('95', 'Pandala : une île pas comme les autres');
INSERT INTO `quest_name` VALUES ('96', 'Plongée sous-marine');
INSERT INTO `quest_name` VALUES ('97', 'Pandala : Sa Déesse...');
INSERT INTO `quest_name` VALUES ('98', 'Pandala: ses Villages...');
INSERT INTO `quest_name` VALUES ('99', 'Sources étranges');
INSERT INTO `quest_name` VALUES ('100', 'Pandala, son air pur...');
INSERT INTO `quest_name` VALUES ('101', 'Henual et l\'Horloge divine');
INSERT INTO `quest_name` VALUES ('102', 'Pandawa et fier de l\'être');
INSERT INTO `quest_name` VALUES ('103', 'Pandawa et fier de l\'être (Episode 2)');
INSERT INTO `quest_name` VALUES ('104', 'Disciple Pandawushuka');
INSERT INTO `quest_name` VALUES ('105', 'Pratiquant Pandawushuka');
INSERT INTO `quest_name` VALUES ('106', 'Legende Lenalde');
INSERT INTO `quest_name` VALUES ('107', 'Voir le Dark Vlad et ne pas mourir');
INSERT INTO `quest_name` VALUES ('108', 'Mystères à Pandala');
INSERT INTO `quest_name` VALUES ('109', 'Apprentissage : Ecuyer ');
INSERT INTO `quest_name` VALUES ('110', 'Apprentissage : Espion');
INSERT INTO `quest_name` VALUES ('111', 'Apprentissage : Apprenti');
INSERT INTO `quest_name` VALUES ('112', 'Apprentissage : Surineur');
INSERT INTO `quest_name` VALUES ('113', 'Apprentissage : Espion Sombre');
INSERT INTO `quest_name` VALUES ('114', 'Apprentissage : Apprenti Sombre');
INSERT INTO `quest_name` VALUES ('115', 'Retrouver Rok Gnorok');
INSERT INTO `quest_name` VALUES ('116', 'Retrouver Musha l\'Oni');
INSERT INTO `quest_name` VALUES ('117', 'Retrouver Marzwel le Gobelin');
INSERT INTO `quest_name` VALUES ('118', 'Retrouver Zatoïshwan');
INSERT INTO `quest_name` VALUES ('119', 'Retrouver Aermyne \'Braco\' Scalptaras');
INSERT INTO `quest_name` VALUES ('120', 'Apprentissage : Chevalier de l\'Espoir');
INSERT INTO `quest_name` VALUES ('121', 'Apprentissage : Adepte des Ecrits');
INSERT INTO `quest_name` VALUES ('122', 'Apprentissage : Chasseur de Renégats');
INSERT INTO `quest_name` VALUES ('123', 'Apprentissage : Chevalier du Désespoir');
INSERT INTO `quest_name` VALUES ('124', 'Apprentissage : Adepte des Douleurs');
INSERT INTO `quest_name` VALUES ('125', 'Apprentissage : Chasseur d\'Âmes');
INSERT INTO `quest_name` VALUES ('126', 'L\'arche de Nowa');
INSERT INTO `quest_name` VALUES ('127', 'Le livre d\'Acidrik Fenlapanse');
INSERT INTO `quest_name` VALUES ('128', 'Le prêtre et la tête de Menalt');
INSERT INTO `quest_name` VALUES ('129', 'A la recherche de l\'éleveur');
INSERT INTO `quest_name` VALUES ('130', 'Les prisonniers d\'Astrub');
INSERT INTO `quest_name` VALUES ('133', 'Kartier Tremai se met à table');
INSERT INTO `quest_name` VALUES ('131', 'Visite guidée au château d\'Allister');
INSERT INTO `quest_name` VALUES ('132', 'Gros oeuvres au château d\'Allister');
INSERT INTO `quest_name` VALUES ('134', 'Les Dents de la Mère Verumacha');
INSERT INTO `quest_name` VALUES ('135', 'La potion de lèche-bottes');
INSERT INTO `quest_name` VALUES ('136', 'Comment mettre un requin en bière');
INSERT INTO `quest_name` VALUES ('137', 'La belle ermite');
INSERT INTO `quest_name` VALUES ('138', 'Pauvre pomme (de terre)');
INSERT INTO `quest_name` VALUES ('139', 'De la viande de Dragodinde pour la tablée d\'Allister');
INSERT INTO `quest_name` VALUES ('140', 'Mais où est passé le Minotoror ?');
INSERT INTO `quest_name` VALUES ('141', 'Culture et élevage');
INSERT INTO `quest_name` VALUES ('142', 'La plume est plus forte... parfois');
INSERT INTO `quest_name` VALUES ('143', 'Allez hue !');
INSERT INTO `quest_name` VALUES ('144', 'Chargez !');
INSERT INTO `quest_name` VALUES ('145', 'Piétine titine');
INSERT INTO `quest_name` VALUES ('146', 'Visite non guidée');
INSERT INTO `quest_name` VALUES ('147', 'Des fleurs épineuses');
INSERT INTO `quest_name` VALUES ('148', 'Epicerie fine');
INSERT INTO `quest_name` VALUES ('149', 'Course polaire');
INSERT INTO `quest_name` VALUES ('150', 'Charger la mule');
INSERT INTO `quest_name` VALUES ('151', 'Tire laine');
INSERT INTO `quest_name` VALUES ('152', 'Le tour du monde');
INSERT INTO `quest_name` VALUES ('153', 'Le maître des clefs');
INSERT INTO `quest_name` VALUES ('154', 'Les sbires du maître');
INSERT INTO `quest_name` VALUES ('155', 'Un juge hystérique');
INSERT INTO `quest_name` VALUES ('156', 'Des donjons, encore des donjons');
INSERT INTO `quest_name` VALUES ('157', 'La voie du guerrier');
INSERT INTO `quest_name` VALUES ('158', 'Ca est frugal, une fois');
INSERT INTO `quest_name` VALUES ('161', 'Pinta Gone veut se remplir de bière Bwork');
INSERT INTO `quest_name` VALUES ('162', 'Un avenir de krotte de Trooll');
INSERT INTO `quest_name` VALUES ('163', 'Les Gobelins de la Manufacture ');
INSERT INTO `quest_name` VALUES ('164', 'Bienvenue au Krazybwork saloon');
INSERT INTO `quest_name` VALUES ('165', 'Bworkidais le paxifik');
INSERT INTO `quest_name` VALUES ('166', 'Manque de moule');
INSERT INTO `quest_name` VALUES ('167', 'Titi Gobelait le magobelin ');
INSERT INTO `quest_name` VALUES ('169', 'Une baguette pour Chef Bworkestre');
INSERT INTO `quest_name` VALUES ('168', 'Manque de peaux');
INSERT INTO `quest_name` VALUES ('170', 'Ange de Gobriel');
INSERT INTO `quest_name` VALUES ('172', 'Premières armes.');
INSERT INTO `quest_name` VALUES ('173', 'Soyez Aouaire !');
INSERT INTO `quest_name` VALUES ('174', 'Instincts primaires.');
INSERT INTO `quest_name` VALUES ('176', 'Manufacture.');
INSERT INTO `quest_name` VALUES ('175', 'Allez, au turbin.');
INSERT INTO `quest_name` VALUES ('177', 'Gobmichet vibre pour Gobrose');
INSERT INTO `quest_name` VALUES ('178', 'Service commandé.');
INSERT INTO `quest_name` VALUES ('179', 'Par Monts et par vaux.');
INSERT INTO `quest_name` VALUES ('180', 'Milice populaire.');
INSERT INTO `quest_name` VALUES ('181', 'Papotage.');
INSERT INTO `quest_name` VALUES ('182', 'Zaap de là !');
INSERT INTO `quest_name` VALUES ('183', 'Bienvenue !');
INSERT INTO `quest_name` VALUES ('184', 'Piou ?');
INSERT INTO `quest_name` VALUES ('185', 'Eau du bain.');
INSERT INTO `quest_name` VALUES ('186', 'Ca va couper, chérie.');
INSERT INTO `quest_name` VALUES ('188', 'Battre le blé.');
INSERT INTO `quest_name` VALUES ('189', 'Salut les copains.');
INSERT INTO `quest_name` VALUES ('190', 'Un décès temporaire.');
INSERT INTO `quest_name` VALUES ('191', 'Oser défier un Osa.');
INSERT INTO `quest_name` VALUES ('192', 'Marché équitable.');
INSERT INTO `quest_name` VALUES ('193', 'La clef du donjon.');
INSERT INTO `quest_name` VALUES ('194', 'Restauration.');
INSERT INTO `quest_name` VALUES ('195', 'Service commandé.');
INSERT INTO `quest_name` VALUES ('196', 'Service commandé.');
INSERT INTO `quest_name` VALUES ('197', 'Service commandé.');
INSERT INTO `quest_name` VALUES ('198', 'Spéléologie.');
INSERT INTO `quest_name` VALUES ('199', 'Les beaux arts.');
INSERT INTO `quest_name` VALUES ('200', 'La complainte de Lykhen');
INSERT INTO `quest_name` VALUES ('202', 'Manufacture.');
INSERT INTO `quest_name` VALUES ('203', 'Manufacture.');
INSERT INTO `quest_name` VALUES ('204', 'Manufacture.');
INSERT INTO `quest_name` VALUES ('205', 'Allez, au turbin.');
INSERT INTO `quest_name` VALUES ('206', 'Allez, au turbin.');
INSERT INTO `quest_name` VALUES ('207', 'Allez, au turbin.');
INSERT INTO `quest_name` VALUES ('208', 'Le Guide du Roublard');
INSERT INTO `quest_name` VALUES ('209', 'Crypte Honnie');
INSERT INTO `quest_name` VALUES ('211', 'Traître ou pas traître, telle est la question...');
INSERT INTO `quest_name` VALUES ('215', 'Emissaire du roi');
INSERT INTO `quest_name` VALUES ('216', 'Info pour un vrai traître');
INSERT INTO `quest_name` VALUES ('217', 'Usuwpation d\'identité');
INSERT INTO `quest_name` VALUES ('218', 'Tomber sur un bec');
INSERT INTO `quest_name` VALUES ('219', 'A roublard, roublard et demi');
INSERT INTO `quest_name` VALUES ('221', 'Le Pwince Monseigneuw');
INSERT INTO `quest_name` VALUES ('220', 'Trouble-fête');
INSERT INTO `quest_name` VALUES ('222', 'Suite Woyale');
INSERT INTO `quest_name` VALUES ('224', 'Un mawiage pwincier');
INSERT INTO `quest_name` VALUES ('225', 'Qui veut la peau du Wabbit?');
INSERT INTO `quest_name` VALUES ('226', 'Quete test');
INSERT INTO `quest_name` VALUES ('229', 'Le déguisement du Koalak');
INSERT INTO `quest_name` VALUES ('230', 'Le Gardien du Pont de la Mort');
INSERT INTO `quest_name` VALUES ('231', 'Le nouveau monde');
INSERT INTO `quest_name` VALUES ('232', 'L\'île des naufragés');
INSERT INTO `quest_name` VALUES ('233', 'Le Chevalier Noir et Rose');
INSERT INTO `quest_name` VALUES ('234', 'La Potion Bulbique');
INSERT INTO `quest_name` VALUES ('235', 'Polka Merer a besoin de vous');
INSERT INTO `quest_name` VALUES ('236', 'Paulette Pain-bèche la boulangère');
INSERT INTO `quest_name` VALUES ('237', 'Le fils caché');
INSERT INTO `quest_name` VALUES ('239', 'Scaéroplane à très grande vitesse');
INSERT INTO `quest_name` VALUES ('238', 'La femme perdue');
INSERT INTO `quest_name` VALUES ('240', 'Un autre moyen de transport');
INSERT INTO `quest_name` VALUES ('241', 'Les Chasses de Crocodaille Dandi');
INSERT INTO `quest_name` VALUES ('242', 'La vengeance du Kito');
INSERT INTO `quest_name` VALUES ('243', 'La vengeance de Peggy la Porkass');
INSERT INTO `quest_name` VALUES ('245', 'La faux Maudite');
INSERT INTO `quest_name` VALUES ('246', 'Triple X.');
INSERT INTO `quest_name` VALUES ('247', 'X comme Xephirès.');
INSERT INTO `quest_name` VALUES ('248', 'Opération commando.');
INSERT INTO `quest_name` VALUES ('249', 'La récompense du compétent.');
INSERT INTO `quest_name` VALUES ('250', 'Rencontre du premier type.');
INSERT INTO `quest_name` VALUES ('251', 'Joyau... ze fête.');
INSERT INTO `quest_name` VALUES ('252', 'Le cristal de Kain Dharyn.');
INSERT INTO `quest_name` VALUES ('253', 'Cambriolage.');
INSERT INTO `quest_name` VALUES ('254', 'La punition de l\'incompétent.');
INSERT INTO `quest_name` VALUES ('255', 'Livraison rapide.');
INSERT INTO `quest_name` VALUES ('256', 'Le moment de vérité.');
INSERT INTO `quest_name` VALUES ('257', 'Vin diou.');
INSERT INTO `quest_name` VALUES ('258', 'Les Ecas ne flippent pas.');
INSERT INTO `quest_name` VALUES ('259', 'Plaine de chats.');
INSERT INTO `quest_name` VALUES ('260', 'A l\'endroit, à l\'envers.');
INSERT INTO `quest_name` VALUES ('261', 'Dans la gueule du chat.');
INSERT INTO `quest_name` VALUES ('262', 'Alimentaire mon cher.');
INSERT INTO `quest_name` VALUES ('263', 'Bouc à misère.');
INSERT INTO `quest_name` VALUES ('264', 'Flagrant délire.');
INSERT INTO `quest_name` VALUES ('265', 'Quand y\'en a marre de Brâkmar.');
INSERT INTO `quest_name` VALUES ('266', 'La capture.');
INSERT INTO `quest_name` VALUES ('267', 'Le carnage des plaines.');
INSERT INTO `quest_name` VALUES ('268', 'Dans la peau de Sphincter Cell.');
INSERT INTO `quest_name` VALUES ('270', 'Mon nom est poison.');
INSERT INTO `quest_name` VALUES ('271', 'Un maître ès pion.');
INSERT INTO `quest_name` VALUES ('272', 'Assassinat effectué.');
INSERT INTO `quest_name` VALUES ('273', 'Le magnanime.');
INSERT INTO `quest_name` VALUES ('274', 'Les kamas résolvent tout.');
INSERT INTO `quest_name` VALUES ('275', 'Supermilicien.');
INSERT INTO `quest_name` VALUES ('276', 'Le forgeron.');
INSERT INTO `quest_name` VALUES ('277', 'Paranoïa aigüe.');
INSERT INTO `quest_name` VALUES ('278', 'A la manière des Brâkmariens.');
INSERT INTO `quest_name` VALUES ('279', 'Le trésor de La Descemer.');
INSERT INTO `quest_name` VALUES ('280', 'Le port salue.');
INSERT INTO `quest_name` VALUES ('281', 'L\'équipe ment.');
INSERT INTO `quest_name` VALUES ('282', 'Une partie de cache-cache.');
INSERT INTO `quest_name` VALUES ('283', 'Pour vivre heureux.');
INSERT INTO `quest_name` VALUES ('284', 'La tactique des gens d\'armes.');
INSERT INTO `quest_name` VALUES ('285', 'La panoplie du milicien.');
INSERT INTO `quest_name` VALUES ('286', 'Ambition ambigüe.');
INSERT INTO `quest_name` VALUES ('289', 'La Grafioze.');
INSERT INTO `quest_name` VALUES ('290', 'Trâknar.');
INSERT INTO `quest_name` VALUES ('291', 'Attaque à retardement.');
INSERT INTO `quest_name` VALUES ('293', 'Une rumeur intéressante.');
INSERT INTO `quest_name` VALUES ('294', 'Investigations à Moon.');
INSERT INTO `quest_name` VALUES ('295', 'Manière douce.');
INSERT INTO `quest_name` VALUES ('296', 'Histoires de tortues.');
INSERT INTO `quest_name` VALUES ('298', 'Course-poursuite.');
INSERT INTO `quest_name` VALUES ('299', 'A la poursuite d\'Octolliard rouge.');
INSERT INTO `quest_name` VALUES ('302', 'Bandanarthrie.');
INSERT INTO `quest_name` VALUES ('303', 'Une Corne Edfrit sans sel.');
INSERT INTO `quest_name` VALUES ('304', 'Un sombre pouvoir.');
INSERT INTO `quest_name` VALUES ('305', 'Une rumeur alléchante.');
INSERT INTO `quest_name` VALUES ('306', 'Enquête à Moon.');
INSERT INTO `quest_name` VALUES ('307', 'Manière forte.');
INSERT INTO `quest_name` VALUES ('308', 'Retour aux origines.');
INSERT INTO `quest_name` VALUES ('309', 'Une faille dans sa carapace.');
INSERT INTO `quest_name` VALUES ('310', 'Les documents avant tout.');
INSERT INTO `quest_name` VALUES ('311', 'Les ordres sont-ils les ordres ?');
INSERT INTO `quest_name` VALUES ('312', 'On m\'appelle l\'Escargot');
INSERT INTO `quest_name` VALUES ('313', 'Contre-espion.');
INSERT INTO `quest_name` VALUES ('314', 'Histoires de salaces.');
INSERT INTO `quest_name` VALUES ('315', 'Affrontement !');
INSERT INTO `quest_name` VALUES ('317', 'Légitime défense.');
INSERT INTO `quest_name` VALUES ('333', 'Le subterfuge de la corne.');
INSERT INTO `quest_name` VALUES ('375', 'Cliquetis fou.');
INSERT INTO `quest_name` VALUES ('376', 'Le professionnel.');
INSERT INTO `quest_name` VALUES ('377', 'Un coup de fouet.');
INSERT INTO `quest_name` VALUES ('378', 'Le dentiste dément.');
INSERT INTO `quest_name` VALUES ('379', 'La revanche de Mak.');
INSERT INTO `quest_name` VALUES ('380', 'La noirceur des armes blanches.');
INSERT INTO `quest_name` VALUES ('381', 'La mise à mort.');
INSERT INTO `quest_name` VALUES ('382', 'Les gardes d\'honneur... à punir.');
INSERT INTO `quest_name` VALUES ('383', 'Un oubli regrettable.');
INSERT INTO `quest_name` VALUES ('384', 'Le con tondant.');
INSERT INTO `quest_name` VALUES ('385', 'Sombres échanges.');
INSERT INTO `quest_name` VALUES ('386', 'Mais si, ce sont des vitamines...');
INSERT INTO `quest_name` VALUES ('387', 'Agent double et demi.');
INSERT INTO `quest_name` VALUES ('388', 'Livreur de mauvaise nouvelle.');
INSERT INTO `quest_name` VALUES ('389', 'Une collection digne de Xilébo.');
INSERT INTO `quest_name` VALUES ('390', 'La chasse, tout un art...');
INSERT INTO `quest_name` VALUES ('391', 'Le tabi mangeur de blops.');
INSERT INTO `quest_name` VALUES ('392', 'Alchimie malfaisante.');
INSERT INTO `quest_name` VALUES ('393', 'Des capes typiques.');
INSERT INTO `quest_name` VALUES ('394', 'Le testament du papa.');
INSERT INTO `quest_name` VALUES ('395', 'Amadouer ou corrompre ?');
INSERT INTO `quest_name` VALUES ('396', 'Taxe gratuite.');
INSERT INTO `quest_name` VALUES ('398', 'Le dur travail d\'éplucheur de patates.');
INSERT INTO `quest_name` VALUES ('397', 'Par la force ou par la finesse ?');
INSERT INTO `quest_name` VALUES ('399', 'Cruel, mais à quel point ?');
INSERT INTO `quest_name` VALUES ('400', 'Activités volcaniques.');
INSERT INTO `quest_name` VALUES ('401', 'Chasse à l\'espion.');
INSERT INTO `quest_name` VALUES ('402', 'Un petit oubli.');
INSERT INTO `quest_name` VALUES ('403', 'Le défi du maître guerrier.');
INSERT INTO `quest_name` VALUES ('404', 'Bois de chauffage.');
INSERT INTO `quest_name` VALUES ('405', 'L\'équipement du traine-savate standard.');
INSERT INTO `quest_name` VALUES ('406', 'L\'espionnage nouveau.');
INSERT INTO `quest_name` VALUES ('407', 'Un assassin... chez Bonta ?');
INSERT INTO `quest_name` VALUES ('408', 'Pauvre larve.');
INSERT INTO `quest_name` VALUES ('409', 'Pauvre larve... dorée.');
INSERT INTO `quest_name` VALUES ('410', 'Un dentier pour l\'ami Mak.');
INSERT INTO `quest_name` VALUES ('411', 'Humiliation sans précédent.');
INSERT INTO `quest_name` VALUES ('412', 'Un choix difficile.');
INSERT INTO `quest_name` VALUES ('413', 'Au combat !');
INSERT INTO `quest_name` VALUES ('414', 'A la rescousse d\'un incapable.');
INSERT INTO `quest_name` VALUES ('433', 'Apprentissage : Disciple de Ménalt');
INSERT INTO `quest_name` VALUES ('434', 'Apprentissage : Disciple de Jiva');
INSERT INTO `quest_name` VALUES ('435', 'Apprentissage : Disciple de Silvosse');
INSERT INTO `quest_name` VALUES ('436', 'Apprentissage : Disciple de Djaul');
INSERT INTO `quest_name` VALUES ('437', 'Apprentissage : Disciple d\'Hécate');
INSERT INTO `quest_name` VALUES ('438', 'Apprentissage : Disciple de Brumaire');
INSERT INTO `quest_name` VALUES ('439', 'L\'éternelle moisson.');
INSERT INTO `quest_name` VALUES ('440', 'Une collecte discutable.');
INSERT INTO `quest_name` VALUES ('441', 'Brâkmar a vraiment besoin de vous !');
INSERT INTO `quest_name` VALUES ('442', 'Bonta a vraiment besoin de vous !');
INSERT INTO `quest_name` VALUES ('445', 'Les 7 bandits.');
INSERT INTO `quest_name` VALUES ('446', 'Le forgeron aux deux mains gauches.');
INSERT INTO `quest_name` VALUES ('447', 'Brâkmar a besoin de vous.');
INSERT INTO `quest_name` VALUES ('448', 'Bonta a besoin de vous.');
INSERT INTO `quest_name` VALUES ('449', 'Chasseur de têtes.');
INSERT INTO `quest_name` VALUES ('458', 'Chasse au dopeul Crâ.');
INSERT INTO `quest_name` VALUES ('459', 'Chasse au dopeul Ecaflip.');
INSERT INTO `quest_name` VALUES ('460', 'Chasse au dopeul Iop.');
INSERT INTO `quest_name` VALUES ('461', 'Chasse au dopeul Osamodas.');
INSERT INTO `quest_name` VALUES ('462', 'Chasse au dopeul Eniripsa.');
INSERT INTO `quest_name` VALUES ('464', 'Chasse au dopeul Enutrof.');
INSERT INTO `quest_name` VALUES ('463', 'Chasse au dopeul Sacrieur.');
INSERT INTO `quest_name` VALUES ('465', 'Chasse au dopeul Sadida.');
INSERT INTO `quest_name` VALUES ('466', 'Chasse au dopeul Pandawa.');
INSERT INTO `quest_name` VALUES ('467', 'Chasse au dopeul Sram.');
INSERT INTO `quest_name` VALUES ('468', 'Chasse au dopeul Xélor.');
INSERT INTO `quest_name` VALUES ('469', 'Chasse au dopeul Féca.');
INSERT INTO `quest_name` VALUES ('470', 'Un bon gros par Douze.');
INSERT INTO `quest_name` VALUES ('471', 'Dévotion.');
INSERT INTO `quest_name` VALUES ('486', 'Le secret de Persimol');
INSERT INTO `quest_name` VALUES ('489', 'Bien débuter');
INSERT INTO `quest_name` VALUES ('490', 'Ne pas traduire');
INSERT INTO `quest_name` VALUES ('492', 'Vaincre le monstre.');
INSERT INTO `quest_name` VALUES ('493', 'Des racines et des ouailles.');
INSERT INTO `quest_name` VALUES ('494', 'Le Grand Manitou.');
INSERT INTO `quest_name` VALUES ('495', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('496', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('497', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('498', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('499', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('500', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('501', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('502', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('503', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('504', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('505', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('506', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('507', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('508', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('509', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('510', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('511', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('512', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('513', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('514', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('515', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('516', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('517', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('518', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('519', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('520', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('521', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('522', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('523', 'Joyeux Nowel.');
INSERT INTO `quest_name` VALUES ('528', 'La grande castagne');
INSERT INTO `quest_name` VALUES ('530', 'Les Douze Gladiatrools');
INSERT INTO `quest_name` VALUES ('529', 'Chasseur tragique');
INSERT INTO `quest_name` VALUES ('532', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('533', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('534', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('535', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('536', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('537', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('538', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('539', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('540', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('541', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('542', 'Marathon quotidien');
INSERT INTO `quest_name` VALUES ('544', 'Le tour du monde du Téléboune');
INSERT INTO `quest_name` VALUES ('531', 'Marathon quotidien');